export const title="Proof of the Basis Representation Theorem";
const content = [
  ['h1', 'Proof of the Basis Representation Theorem'],
  ["pmain","According to the division algorithm, given some positive integer \\(b\\), any positive integer \\(n\\) can be represented as:"],
  ["displayFormula","$$ n = q_0 b + a_0 $$"],
  ["pmain","where \\(a_0\\) and \\(q_0\\) are unique integers and \\(a_0\\) is less than \\(b\\). Similarly, for \\(q_0\\):"],
  ["displayFormula","$$ q_0 = q_1 b + a_1 $$"],
  ["pmain","We keep divding by \\(b\\) until we reach \\(q_k\\) where \\(q_k = 0\\):"],
  ["displayFormula","$$\\begin{gather} q_1 = q_2 b + a_2 \\\\ q_2 = q_3 b + a_3 \\\\ \\vdots \\\\ q_{k-1} = 0 * b + a_k \\end{gather}$$"],
  ["pmain","Note that \\(q_i > q_{i+1}\\)."],
  ["pmain","Now replace \\(q_0\\) in the first equation using the second equation:"],
  ["displayFormula","$$\\begin{align} n &= (q_1 b + a_1)b + a_0 \\\\ &= q_1 b^2 + a_1b + a_0 \\end{align}$$"],
  ["pmain","Similarly, we replace \\(q_1\\):"],
  ["displayFormula","$$\\begin{align} n &= (q_2 b + a_2) b^2 + a_1b + a_0 \\\\ &= q_2 b^3 + a_2b^2 + a_1b + a_0 \\end{align}$$"],
  ["pmain","If we repeat this process, we get:"],
  ["displayFormula","$$n = a_kb^k + a_{k-1} b^{k-1} + \\cdots + a_3 b^3 + a_2b^2 + a_1b + a_0 $$"],
  ["pmain","This proves the Basis Representation Theorem. To further establish the uniqueness, assume there is another representation using the same base:"],
  ["displayFormula","$$n = c_kb^k + c_{k-1} b^{k-1} + \\cdots + c_3 b^3 + c_2b^2 + c_1b + c_0 $$"],
  ["pmain","Subtracting the first representation from the second:"],
  ["displayFormula","$$0 = (a_k - c_k)b^k + (a_{k-1} - c_{k-1}) b^{k-1} + \\cdots + (a_2-c_2)b^2 + (a_1-c_1)b + (a_0-c_0) $$"],
  ["pmain","Let \\(j\\) be the smallest integer where \\(a_j\\) and \\(c_j\\) differ:"],
  ["displayFormula","$$0 = (a_k - c_k)b^k + (a_{k-1} - c_{k-1}) b^{k-1} + \\cdots + (a_j-c_j)b^j + \\cdots + (a_2-c_2)b^2 + (a_1-c_1)b + (a_0-c_0) $$"],
  ["pmain","If \\(j\\) is the smallest integer where \\(a_j\\) and \\(c_j\\) differ, then \\(a_i - c_i = 0\\) for all \\(i \\lt j\\):"],
  ["displayFormula","$$0 = (a_k - c_k)b^k + (a_{k-1} - c_{k-1}) b^{k-1} + \\cdots + (a_j-c_j)b^j $$"],
  ["pmain","Dividing both sides by \\(b^j\\):"],
  ["displayFormula","$$ 0 = (a_k - c_k)b^{k-j} + (a_{k-1} - c_{k-1}) b^{k-j-1} + \\cdots + (a_j-c_j)$$"],
  ["pmain","Bring \\(a_j-c_j\\) to the other side:"],
  ["displayFormula","$$\\begin{align} -(a_j-c_j) &= (a_k - c_k)b^{k-j} + (a_{k-1} - c_{k-1}) b^{k-j-1} + \\cdots + (a_{j+1}-c_{j+1})b \\\\ c_j-a_j &= hb \\end{align}$$"],
  ["pmain","This means \\(c_j-a_j\\) is a multiple of \\(b\\). Since \\(0 \\le c_j \\lt b\\) and \\(0 \\le a_j \\lt b\\), then:"],
  ["displayFormula","$$\\begin{align} -a_j \\le c_j - a_j &\\lt b - a_j \\\\ -b \\lt -a_j \\le c_j - a_j &\\lt b - a_j \\lt b \\\\ -b \\lt c_j - a_j &\\lt b \\end{align}$$"],
  ["pmain","If \\(c_j-a_j\\) is a multiple of \\(b\\) and \\(-b \\lt c_j - a_j \\lt b\\), then it's only possible that \\(c_j - a_j=0\\). This shows that \\(c_j\\) and \\(a_j\\) are equal."],
];
export default content;