export const title="Deriving The Expected Value And Variance Of The Binomial Distribution";
const content = [
  ['h1', 'The Mean And Variance Of The Binomial Distribution'],
  ["pmain","If \\(X \\sim B(n,p)\\), then:"],
  ["displayFormula","\\[ P(X=x) = {n \\choose x} p^x (1-p)^{n-x} \\]"],
  ["pmain","Where \\(x\\) is the number of successes. We can rewrite this as:"],
  ["displayFormula","\\[ P(X=x) = \\frac{n!}{x!(n-x)!} p^x (1-p)^{n-x} \\]"],
  ["pmain","This means that the formula for the expected value is:"],
  ["displayFormula","\\[ E[X] = \\sum_{x=0}^n (x) \\left( \\frac{n!}{x!(n-x)!} p^x (1-p)^{n-x} \\right) \\]"],
  ["pmain","Instead of starting with \\(x=0\\), we can start with \\(x=1\\):"],
  ["displayFormula","\\[ E[X] = \\sum_{x=1}^n (x) \\left( \\frac{n!}{x!(n-x)!} p^x (1-p)^{n-x} \\right) \\]"],
  ["pmain","We can also divide the first \\(x\\):"],
  ["displayFormula","\\[ E[X] = \\sum_{x=1}^n \\left( \\frac{n!}{(x-1)!(n-x)!} p^x (1-p)^{n-x} \\right) \\]"],
  ["pmain","Let's take \\(np\\) out:"],
  ["displayFormula","\\[ E[X] = np \\sum_{x=1}^n \\left( \\frac{(n-1)!}{(x-1)!(n-x)!} p^{x-1} (1-p)^{n-x} \\right) \\]"],
  ["pmain","This will allow us to rewrite our equation as:"],
  ["displayFormula","\\[ E[X] = np \\sum_{x=1}^n {n-1 \\choose x-1} p^{x-1} (1-p)^{n-x} \\]"],
  ["pmain","Now let \\(m=n-1\\) and \\(y=x-1\\):"],
  ["displayFormula","\\[ E[X] = np \\sum_{x=1}^n {m \\choose y} p^y (1-p)^{m-y} \\]"],
  ["pmain","We are summing from \\(x=1\\) till \\(x=n\\), but if we use \\(y\\) instead, then the summing is from \\(y+1=1\\) till \\(y+1=n\\) or from \\(y=0\\) till \\(y=m\\):"],
  ["displayFormula","\\[ E[X] = np \\sum_{y=0}^m {m \\choose y} p^y (1-p)^{m-y} \\]"],
  ["pmain","If we use the binomial theorem:"],
  ["displayFormula","\\[ np \\sum_{y=0}^m {m \\choose y} p^y (1-p)^{m-y} = np (p + (1-p))^m \\]"],
  ["pmain","This gives us the expected value:"],
  ["displayFormula","\\[ E[X] = np \\]"],
  ["pmain","As for the variance, we can use this equation:"],
  ["displayFormula","\\[ Var[X] = E[X^2] - E[X]^2 \\]"],
  ["pmain","The equation for \\(E[X^2]\\) is:"],
  ["displayFormula","\\[ E[X^2] = \\sum_{x=0}^n (x^2) P(X=x) \\]"],
  ["pmain","Instead of evaluating \\(E[X^2]\\) directly, we can use \\(E[X^2-X]\\) to find \\(E[X^2]\\):"],
  ["displayFormula","\\[ E[X(X-1)] = \\sum_{x=0}^n (x)(x-1) \\left( \\frac{n!}{x!(n-x)!} p^x (1-p)^{n-x} \\right) \\]"],
  ["pmain","We can divide \\((x)(x-1)\\):"],
  ["displayFormula","\\[ E[X(X-1)] = \\sum_{x=0}^n \\left( \\frac{n!}{(x-2)!(n-x)!} p^x (1-p)^{n-x} \\right) \\]"],
  ["pmain","Let's take \\(n(n-1)p^2\\) out:"],
  ["displayFormula","\\[ E[X(X-1)] = n(n-1)p^2 \\sum_{x=0}^n \\left( \\frac{(n-2)!}{(x-2)!(n-x)!} p^{x-2} (1-p)^{n-x} \\right) \\]"],
  ["pmain","Now let \\(m=n-2\\) and \\(y=x-2\\):"],
  ["displayFormula","\\[ E[X(X-1)] = n(n-1)p^2 \\sum_{x=0}^n {m \\choose y} p^{y} (1-p)^{m-y} \\]"],
  ["pmain","Using the binomial theorem like before, we can conclude:"],
  ["displayFormula","\\[ E[X(X-1)] = n(n-1)p^2 (1) \\]"],
  ["pmain","The Linearity of Expectation tells us that:"],
  ["displayFormula","\\[ E[X(X-1)] = E[X^2] - E[X] \\]"],
  ["pmain","This gives us the last step to find \\(E[X^2]\\):"],
  ["displayFormula","$$\\begin{align} E[X^2] &= n(n-1)p^2 + E[X] \\\\ E[X^2] &= n(n-1)p^2 + np \\end{align}$$"],
  ["pmain","Now we can evaluate \\(E[X^2]-(E[X]^2)\\):"],
  ["displayFormula","$$\\begin{align} E[X^2] - (E[X]^2) &= n(n-1)p^2 + np - n^2p^2 = n^2p^2-np^2 + np - n^2p^2 \\\\ E[X^2] - (E[X]^2) &= np-np^2 = np(1-p) \\end{align}$$"],
  ["pmain","This means \\(Var[X]=npq\\). I would like to thank <a href='https://www.youtube.com/watch?v=8fqkQRjcR1M'>jbstatistics</a> for helping me with this."],
];
export default content;