export const title="If X is a positive continuous random variable with a memoryless property, then X is exponentially distributed";
const content = [
  ['h1', 'If X Is A Positive Continuous Random Variable With A Memoryless Property, Then X Is Exponentially Distributed'],
  ["pmain","A memoryless property means:"],
  ["displayFormula","$$P(X \\gt t + s | X \\gt s) = P(X \\gt t)$$"],
  ["pmain","So we can use this to state:"],
  ["displayFormula","$$\\begin{align} P(X \\gt t + s) &= P(X \\gt s) P(X \\gt t + s | X \\gt s) \\\\ &= P(X \\gt s) P(X \\gt t) \\end{align}$$"],
  ["pmain","Let \\(G_x(t) = P(X \\gt t)\\):"],
  ["displayFormula","$$G(t + s) = G(s) G(t)$$"],
  ["pmain","If \\(s = t\\)"],
  ["displayFormula","$$G(2t) = G(t)^2$$"],
  ["pmain","If \\(s = 2t\\)"],
  ["displayFormula","$$G(3t) = G(2t)G(t) = G(t)^3$$"],
  ["pmain","In general \\(G(kt) = G(t)^k\\). Now let's say we raise both sides to the power of \\(1/k\\), and replace \\(t\\) with \\(h/k\\):"],
  ["displayFormula","$$G(h)^{\\frac{1}{k}} = G \\left(\\frac{h}{k} \\right)$$"],
  ["pmain","This means:"],
  ["displayFormula","$$G(j)^{\\frac{m}{k}} = G \\left(j\\frac{m}{k} \\right)$$$$G(j)^x = G \\left(jx \\right) \\text{ for all rational } x \\gt 0$$"],
  ["pmain","Let \\(j=1\\):"],
  ["displayFormula","$$G(x) = G(1)^x$$$$P(X \\gt x) = e^{xln(G(1))}$$"],
  ["pmain","Since \\(G(1)\\) is between 0 and 1, then \\(ln(G(1))\\) is some negative constant:"],
  ["displayFormula","$$P(X \\gt x) = e^{-\\lambda x}$$"],
  ["pmain","I got my derivation from <a href='https://youtu.be/N8O6zd6vTZ8?t=9m46s'>this video</a>. From the above, we can get the cumulative distribution function:"],
  ["displayFormula","$$F(x) = P(X \\le x) = 1 - e^{-\\lambda x}$$"],
  ["pmain","We can derivate this to get the pdf:"],
  ["displayFormula","$$f(x) = \\lambda e^{-\\lambda x}$$"],
];
export default content;