export const title="Solving the logistic differential equation";
const content = [
  ['h1', 'Solving The Logistic Differential Equation'],
  ['pmain', 'Let \\(K\\) represent the carrying capacity for a particular organism in a given environment, and let \\(r\\) be a real number that represents the growth rate. The function \\(P(t)\\) represents the population of this organism as a function of time \\(t\\). The logistic differential equation is:'], 
  ["displayFormula","\\[ \\frac{dP}{dt} =rP \\left( 1 - \\frac{P}{K} \\right) \\]"],
  ['pmain', 'To solve this let\'s first start by rewriting the equation:'], 
  ["displayFormula","\\[ \\frac{dP}{dt} = \\frac{rP(K-P)}{K} \\]"],
  ['pmain', 'Rearranging:'], 
  ["displayFormula","\\[ \\frac{K}{P(K-P)} \\ dP = r \\ dt \\]"],
  ['pmain', 'Now we can take the integral of both sides:'], 
  ["displayFormula","\\[ \\int \\frac{K}{P(K-P)} \\ dP = \\int r \\ dt \\]"],
  ['pmain', 'We can use partial fraction decomposition on the left-hand side:'], 
  ["displayFormula","\\[ \\int \\frac{1}{P} + \\frac{1}{K-P} \\ dP = \\int r \\ dt \\]"],
  ['pmain', 'Evaluating:'], 
  ["displayFormula","\\[\\begin{aligned} \\ln|P| - \\ln|K-P| &= rt + C \\\\ \\ln \\left| \\frac{P}{K-P} \\right| &=rt+C\\end{aligned} \\]"],
  ['pmain', 'Now exponentiate both sides:'], 
  ["displayFormula","\\[\\begin{aligned} \\left| \\frac{P}{K-P} \\right| &= e^{rt+C} = e^{rt}e^C \\\\ &= e^{rt}D\\end{aligned} \\]"],
  ['pmain', 'Since \\(P > 0\\) and \\(K \\gt P\\), then \\(\\frac{P}{K-P} > 0\\):'], 
  ["displayFormula","\\[ \\frac{P}{K-P} = e^{rt}D \\]"],
  ['pmain', 'If we make \\(P\\) the subject:'], 
  ["displayFormula","\\[\\begin{aligned} P &= DKe^{rt} - DPe^{rt} \\\\ P (1 + De^{rt}) &= DKe^{rt} \\\\ P &= \\frac{DKe^{rt}}{1 + De^{rt}} \\end{aligned} \\]"],
  ['pmain', 'To determine the value of \\(D\\), we can set \\(t = 0\\). Let \\(P_0\\) be the initial population:'], 
  ["displayFormula","\\[\\begin{aligned} \\frac{P_0}{K-P_0} &= e^{r(0)}D \\\\ \\frac{P_0}{K-P_0} &= D \\end{aligned}\\]"],
  ['pmain', 'Substituting the expression for \\(D\\) into the equation for \\(P\\):'], 
  ["displayFormula","\\[P = \\frac{\\frac{P_0}{K-P_0} Ke^{rt}}{1 + \\frac{P_0}{K-P_0} e^{rt}} \\]"],
  ['pmain', 'Multiply the numerator and denominator by \\((K-P_0)\\):'], 
  ["displayFormula","\\[P(t) = \\frac{P_0 Ke^{rt}}{(K-P_0) +P_0 e^{rt}} \\]"],
];
export default content;