export const title="Proof That sin(x)/x approaches 1 as x approaches 0";
const content = [
  ['h1', 'Proof That sin(x)/x approaches 1 as x approaches 0'], ['pmain', 'Suppose I have a circle with radius 1 and I want to find the area of the <span style="color:#FF99CC">pink</span> region bounded by the <span style="color:purple">purple line</span> and the\n<span style="color:green">x-axis</span>:'], ['displayimg', 'first.png'], ['pmain', 'Let point M be the point where the <span style="color:purple">purple line</span> touches the\ncircle and let point N be the point where the <span style="color:green">x-axis</span> touches the circle. The\nformula for finding the area of a sector of a circle with raduis 1 is:'], ['displayimg', 'second.png'], ['pmain', 'Now lets make a triangle by connecting points M and N:'], ['displayimg', 'third.png'], ['pmain', 'Since the height of this triangle is [<span style="color:#333399">sin(<span style="color:red">θ</span>)</span>] and the base is 1, then the area of the triangle is:'], ['displayimg', 'fourth.png'], ['pmain', 'We know that A<sub>2</sub> ≤ A<sub>1</sub>. Now lets create a smaller circle inside the main circle which has the radius of [<span style="color:orange">cos(<span style="color:red">θ</span>)</span>]:'], ['displayimg', 'fifth.png'], ['pmain', 'The area bounded by the <span style="color:purple">purple line</span> in the smaller circle and the <span style="color:green">x-axis</span> has the following equation:'], ['displayimg', 'sixth.png'], ['pmain', 'We know that A<sub>3</sub> ≤ A<sub>2</sub> ≤ A<sub>1</sub>, which can be written as:'], ['displayimg', 'seventh.png'], ['pmain', 'Now lets take the limit of all sides as x approaches 0:'], ['displayimg', 'eighth.png'],
  ['pmain', 'Since [lim<sub>θ-&gt;0</sub> (<span style="color:orange">cos(<span style="color:red">θ</span>)</span>) = 1], then, by the squeeze theorem, lim<sub>θ-&gt;0</sub> (<span style="color:#333399">sin(<span style="color:red">θ</span>)</span>/<span style="color:red">θ</span>) has to be 1. Keep in mind that this only works if <span style="color:red">θ</span> is in radians.'],
  ['displayFormula','\\[ \\lim_{\\theta \\to 0} \\frac{ \\color{#333399} \\sin( {\\color{red} \\theta} )}{\\color{red} \\theta} = 1\\]'],
  ['pmain', 'To change an angle from radians to degrees, you multiply it by \\(\\frac{180}{\\pi}\\). Let \\( \\frac{180}{\\pi} \\theta = \\alpha \\), and let\'s say <span style="color:#333399">sin</span> now uses degrees:'],
  ['displayFormula','\\[\\begin{align} \\lim_{\\theta \\to 0} \\frac{ \\color{#333399} \\sin( {\\color{black} \\alpha} )}{\\color{red} \\theta} &= 1 \\\\ \\lim_{\\theta \\to 0}  \\frac{\\frac{180}{\\pi} {\\color{#333399} \\sin( {\\color{black} \\alpha} )}}{ \\frac{180}{\\pi} {\\color{red} \\theta}} = \\lim_{\\theta \\to 0} \\frac{\\frac{180}{\\pi} {\\color{#333399} \\sin( {\\color{black} \\alpha} )}}{ \\alpha } &= \\left(\\frac{180}{\\pi} \\right) \\lim_{\\theta \\to 0} \\frac{ {\\color{#333399} \\sin( {\\color{black} \\alpha} )}}{ \\alpha } = 1 \\end{align}\\]'],
  ['pmain', 'That means if you use degrees, then:'],
  ['displayFormula','\\[ \\lim_{\\theta \\to 0} \\frac{ {\\color{#333399} \\sin( {\\color{black} \\alpha} )}}{ \\alpha } = \\frac{\\pi}{180} \\]'],
];
export default content;