export const title="Deriving the expected value and the variance of the geometric distribution (when success isn't included)";
const content = [
  ['h1', 'Deriving The Mean And The Variance Of The Geometric Distribution (when success isn\'t included)'],
  ["pmain","If \\(X \\sim G(p)\\), then:"],
  ["displayFormula","$$\\begin{align} E[X] &= \\sum_{x=1}^{\\infty} x (1-p)^{x-1}p \\\\ &= 1p + 2p(1-p) + 3p(1-p)^2 + 4p(1-p)^3 + \\ldots \\end{align}$$"],
  ["pmain","If we multiple both sides with \\((1-p)\\):"],
  ["displayFormula","$$\\begin{align} {\\color{blue} (1-p)E[X] } &= {\\color{blue} 1p(1-p) + 2p(1-p)^2 + 3p(1-p)^3 + 4p(1-p)^4 + \\ldots } \\\\ E[X] - (1-p)E[X] &= 1p + 2p(1-p) {\\color{blue} - 1p(1-p) } + 3p(1-p)^2 {\\color{blue} -2p(1-p)^2 } + \\ldots \\\\ E[X] - (1-p)E[X] &= p + p(1-p) + p(1-p)^2 + p(1-p)^3 + \\ldots \\end{align}$$"],
  ["pmain","Let's simplify \\(E[X] - (1-p)E[X]\\):"],
  ["displayFormula","$$\\begin{align} E[X] - (1-p)E[X] &= E[X] - E[X] + p E[X] \\\\ &= p E[X] \\end{align}$$"],
  ["pmain","This means:"],
  ["displayFormula","$$\\begin{align} pE[X] &= p + p(1-p) + p(1-p)^2 + p(1-p)^3 + \\ldots \\\\ E[X] &= 1 + (1-p) + (1-p)^2 + (1-p)^3 + \\ldots \\\\ E[X] &= q^0 + q^1 + q^2 + q^3 + \\ldots\\end{align}$$"],
  ["pmain","This is a geometric series, so using <a href='../../discrete_mathematics/sequence_and_series/the_sum_to_infinity_of_a_geometric_series'>this equation</a> we can conclude:"],
  ["displayFormula","\\[ E[X] = \\frac{1}{1-(1-p)} = \\frac{1}{p} \\]"],
  ["pmain","As for the variance:"],
  ["displayFormula","$$\\begin{align} Var[X] &= E[X^2] - (E[X])^2 \\\\ Var[X] &= E[X(X-1)] + E[X] - (E[X])^2 \\\\ Var[X] &= E[X(X-1)] + \\frac{1}{p} - \\frac{1}{p^2} \\end{align}$$"],
  ["pmain","Now let's try to figure out \\(E[X]\\) (this is going to involve derivatives):"],
  ["displayFormula","$$\\begin{align} E[X(X-1)] &= \\sum^{\\infty}_{x=1} x(x-1) p q^{x-1} \\\\ E[X(X-1)] &= p \\sum^{\\infty}_{x=1} (x-1) x q^{x-1} \\end{align}$$"],
  ["pmain","This is where derivatives get involved:"],
  ["displayFormula","$$\\begin{align} E[X(X-1)] &= p \\sum^{\\infty}_{x=1} (x-1) \\frac{d}{dq} q^x \\\\ &= p \\frac{d}{dq} \\sum^{\\infty}_{x=1} (x-1) q^x \\end{align}$$"],
  ["pmain","We can take \\(q^2\\) out:"],
  ["displayFormula","$$\\begin{align} E[X(X-1)] &= p \\frac{d}{dq} q^2 \\sum^{\\infty}_{x=1} (x-1) q^{x-2} \\end{align}$$"],
  ["pmain","We can use derivatives again:"],
  ["displayFormula","$$\\begin{align} E[X(X-1)] &= p \\frac{d}{dq} \\left( q^2 \\frac{d}{dq} \\sum^{\\infty}_{x=1} q^{x-1} \\right) \\end{align}$$"],
  ["pmain","Let \\(y=x-1\\):"],
  ["displayFormula","$$\\begin{align} E[X(X-1)] &= p \\frac{d}{dq} \\left( q^2 \\frac{d}{dq} \\sum^{\\infty}_{y=0} q^y \\right) \\end{align}$$"],
  ["pmain","There is a geometric series here as well:"],
  ["displayFormula","$$\\begin{align} E[X(X-1)] &= p \\frac{d}{dq} \\left( q^2 \\frac{d}{dq} \\left( \\frac{1}{1-q} \\right) \\right) \\end{align}$$"],
  ["pmain","Let's evaluate the derivatives:"],
  ["displayFormula","$$\\begin{align} E[X(X-1)] &= p \\frac{d}{dq} \\left( q^2 \\left( \\frac{1}{(1-q)^2} \\right) \\right) \\\\ E[X(X-1)] &= p \\left( \\frac{2q}{(1-q)^3} \\right) \\end{align}$$"],
  ["pmain","Since \\(p=1-q\\):"],
  ["displayFormula","$$\\begin{align} E[X(X-1)] &= p \\left( \\frac{2(1-p)}{p^3} \\right) \\\\ &= \\left( \\frac{2-2p}{p^2} \\right) \\end{align}$$"],
  ["pmain","Going back to variance:"],
  ["displayFormula","$$\\begin{align} Var[X] &= E[X(X-1)] + \\frac{1}{p} - \\frac{1}{p^2} = \\left( \\frac{2-2p}{p^2} \\right) + \\frac{1}{p} - \\frac{1}{p^2} \\\\ &= \\frac{1-2p}{p^2} + \\frac{p}{p^2} = \\frac{1-p}{p^2} \\end{align}$$"],
];
export default content;