export const title="Deriving the expected value and the variance of the exponential distribution";
const content = [
  ['h1', 'Deriving The Expected Value And The Variance Of The Exponential Distribution'],
  ["pmain","The expected value is the probability-weighted average over all possible values:"],
  ["displayFormula","$$ E[X] = \\int_0^{\\infty} x \\cdot (\\lambda e^{- \\lambda x}) dx$$"],
  ["pmain","We can take the constant out:"],
  ["displayFormula","$$ E[X] = \\lambda \\int_0^{\\infty} x \\cdot (e^{- \\lambda x}) dx$$"],
  ["pmain","Evaluate the integral:"],
  ["displayFormula","$$ E[X] = \\lambda \\left[ - \\frac{xe^{- \\lambda x}}{\\lambda} - \\frac{e^{- \\lambda x}}{\\lambda ^ 2} \\right]_0 ^ {\\infty}$$"],
  ["pmain","Plugging in 0 and taking the limit to \\(\\infty\\):"],
  ["displayFormula","$$ E[X] = \\lambda \\left[ \\lim_{x \\to \\infty} \\left( - \\frac{xe^{- \\lambda x}}{\\lambda} - \\frac{e^{- \\lambda x}}{\\lambda ^ 2} \\right) - \\left( - \\frac{(0)e^{- \\lambda (0)}}{\\lambda} - \\frac{e^{- \\lambda (0)}}{\\lambda ^ 2} \\right) \\right]$$"],
  ["pmain","Simplify:"],
  ["displayFormula","$$ E[X] = \\lambda \\left[ (0) - \\left( - 0 - \\frac{1}{\\lambda ^ 2} \\right) \\right] = \\frac{1}{\\lambda}$$"],
  ["pmain","Now to calculate the variance, we need to figure out \\(E[X^2]\\):"],
  ["displayFormula","$$ E[X^2] = \\int x^2 f(x) dx = \\int_0^{\\infty} x^2 \\lambda e^{- \\lambda x} dx $$"],
  ["pmain","Let's add and subtract \\((2x)(e^{-\\lambda x})\\) (this will make the integration easier):"],
  ["displayFormula","$$ E[X^2] = \\int_0^{\\infty} (2x)(e^{-\\lambda x}) + x^2 \\lambda e^{- \\lambda x} - (2x)(e^{-\\lambda x}) dx $$"],
  ["pmain","We can split this:"],
  ["displayFormula","$$ E[X^2] = \\int_0^{\\infty} (2x)(e^{-\\lambda x}) dx + \\int_0^{\\infty} x^2 \\lambda e^{- \\lambda x} - (2x)(e^{-\\lambda x}) dx $$"],
  ["pmain","We can take the \\(2/ \\lambda\\) out in the first integral and we will be left with the expected value:"],
  ["displayFormula","$$\\begin{align} E[X^2] &= \\frac{2}{\\lambda} \\int_0^{\\infty} x \\lambda(e^{-\\lambda x}) dx + \\int_0^{\\infty} x^2 \\lambda e^{- \\lambda x} - (2x)(e^{-\\lambda x}) dx \\\\ &= \\frac{2}{\\lambda} \\left( \\frac{1}{\\lambda} \\right) + \\int_0^{\\infty} x^2 \\lambda e^{- \\lambda x} - (2x)(e^{-\\lambda x}) dx \\end{align}$$"],
  ["pmain","As for the second part, let's make a guess, say \\(xe^{-\\lambda x}\\). Does derivating it give us \\(x^2 \\lambda e^{- \\lambda x} - (2x)(e^{-\\lambda x})\\)?"],
  ["displayFormula","$$ \\frac{d}{dx} xe^{-\\lambda x} = e^{- \\lambda x} + x(-\\lambda)(e^{-\\lambda x})$$"],
  ["pmain","Close! Let's use \\(x^2 e^{-\\lambda x}\\) instead:"],
  ["displayFormula","$$\\begin{align} \\frac{d}{dx} x^2 e^{-\\lambda x} &= (2x) e^{- \\lambda x} + x^2 (-\\lambda)(e^{-\\lambda x}) &= (2x) e^{- \\lambda x} - x^2 (\\lambda)(e^{-\\lambda x}) \\end{align}$$"],
  ["pmain","If we multiply both sides with -1, we get \\(x^2 \\lambda e^{- \\lambda x} - (2x)(e^{-\\lambda x})\\). So the integral of the second part is \\(-x^2 e^{-\\lambda x}\\):"],
  ["displayFormula","$$\\begin{align} E[X^2] &= \\frac{2}{\\lambda ^2} + \\left[ -x^2 e^{-\\lambda x} \\right]^\\infty_0 \\\\ E[X^2] &= \\frac{2}{\\lambda ^2} \\end{align}$$"],
  ["pmain","We can use this to calculate variance:"],
  ["displayFormula","$$\\begin{align} Var[X] &= E[X^2] - E[X]^2 = \\frac{2}{\\lambda ^2} - \\left( \\frac{1}{\\lambda} \\right)^2 \\\\ Var[X] &= \\frac{1}{\\lambda^2} \\end{align}$$"],
];
export default content;