export const title="x^2 ≡ -1 mod p is solvable if and only if p = 2 or p ≡ 1 mod 4";
const content = [
  ['h1', 'x<sup>2</sup> ≡ -1 mod p Is Solvable If And Only If p = 2 or p ≡ 1 mod 4'],
  ['pmain', 'Suppose we have a prime \\(p\\) and \\(x^2 ≡ -1 \\bmod p\\). If \\(p=2\\), then the solution would be trivial \\((x = 1)\\).'],
  ['pmain', 'If \\(p> 2\\), then we can consider four possibilities, \\((1 \\bmod 4)\\), \\((2 \\bmod 4)\\), \\((3 \\bmod 4)\\) and \\((4 \\bmod 4)\\). If \\(p > 2\\), then \\(p\\) can only be \\((1 \\bmod 4)\\) or \\((3 \\bmod 4)\\).'],
  ['pmain', 'Let\'s assume \\(p ≡ 3 \\bmod 4\\), then \\(p = 4k + 3\\), which would also mean:'],
  ['displayFormula', '$$ p - 1 = 4k + 2 = 2(2k + 1) $$'],
  ['pmain', 'Since \\(x^2 ≡ -1 \\bmod p\\):'],
  ['displayFormula', '$$\\begin{gather} (x^2)^{(2k + 1)} ≡ (-1)^{(2k + 1)} ≡ -1 \\bmod p \\\\ x^{(4k + 2)} = x^{(p-1)} ≡ -1 \\bmod p\\end{gather}$$'],
  ['pmain', 'But according to Fermat\'s little theorem: \\([x^{(p-1)} ≡ 1 \\bmod p]\\). So we end up with \\([1 ≡ -1 \\bmod p]\\), therefore \\(p=2\\), but contradicts our assumption that \\(p=3 \\bmod 4\\).'],
  ['pmain', 'Now let \\(p ≡ 1 \\bmod 4\\), then \\(p = 4k + 1\\). Thus, \\((p - 1)/2\\) is even. By Wilson\'s Theorem:'],
  ['displayFormula', '$$ (p - 1)! ≡ -1 \\mod p $$'],
  ['pmain', 'If we expand:'],
  ['displayFormula', '$$ (1)(2) \\ldots \\left( \\frac{p-1}{2} \\right) \\left( \\frac{p+1}{2} \\right) \\ldots(p-2)(p - 1) ≡ -1 \\mod p $$'],
  ['pmain', 'Since \\(p - x ≡ -x \\mod p\\):'],
  ['displayFormula', '$$ (1)(2) \\ldots \\left( \\frac{p-1}{2} \\right) \\left( \\frac{p+1}{2} \\right) \\ldots(-2)(-1) ≡ -1 \\mod p $$'],
  ['pmain', 'Let\'s take the negative sign out:'],
  ['displayFormula', '$$ (1)(2) \\ldots \\left( \\frac{p-1}{2} \\right) \\left( \\frac{p-1}{2} \\right) \\ldots(2)(1) \\times (-1)^l ≡ -1 \\mod p $$'],
  ['pmain', 'The second half is the same size as the first and they are both even, so \\(l\\) is even:'],
  ['displayFormula', '$$ \\left ( (1)(2) \\ldots \\left( \\frac{p-1}{2} \\right) \\right)^2 \\times (1) ≡ -1 \\mod p $$'],
  ['pmain', 'which means:'],
  ['displayFormula', '$$ \\left ( \\left( \\frac{p-1}{2} \\right) ! \\right)^2 ≡ -1 \\mod p $$'],
  ['pmain', 'Thus, \\(x^2 ≡ -1 \\bmod p\\) has the solution \\(x = ((p - 1)/2)!\\) when \\(p ≡ 1 \\bmod 4\\).'],
];
export default content;
