export const title="Convergence of a power series";
const content = [
  ['h1', 'Convergence Of A Power Series'],
  ['pmain', 'Consider a power series \\(\\sum c_n (x-a)^n\\). It could be the case that the series only converges at \\(x=a\\), and diverges at every other \\(x\\) value. It could also be the case, that the series converges for all \\(x\\) values. Let\'s assume that neither case is true.'],
  ['pmain', 'Let \\(z = x-a\\), so now the series is \\(\\sum c_n z^n\\). If it is not true that the series converges only when \\(z = 0\\), then there must an integer \\(b\\) such that the series converges when \\(z = b\\). If \\(\\sum c_n b^n\\) converges, then \\(\\lim_{n \\to \\infty} c_n b^n = 0\\) (contrapositive of the divergence test). By the definition of a limit, there must be a positive integer \\(N\\) such that \\(|c_n b^n| \\lt 1\\) whenever \\(n \\ge N\\). This means:'],
  ["displayFormula","\\[\\begin{align} |c_n z^n| = \\left| \\frac{c_n b^n z^n}{b^n} \\right| &= |c_n b^n|\\left| \\frac{z^n}{b^n} \\right| \\\\ &\\lt \\left| \\frac{z^n}{b^n} \\right| \\quad \\text{ when } n \\ge N \\end{align} \\]"],
  ['pmain', 'If \\(|z| < |b|\\), then \\(\\left| \\frac{z}{b} \\right| < 1\\), so \\(\\sum \\left| \\frac{z}{b} \\right| ^n\\) is a convergent geometric series. Since \\(|c_n z^n| < \\left| \\frac{z}{b} \\right|^n\\), then, by the comparison test, \\(\\sum |c_n z^n|\\) is convergent, and thus \\(\\sum c_n z^n\\) is also convergent. Thus we have proven, that if there exists some integer \\(b \\ne 0\\) for which \\(\\sum c_n b^n\\) converges, then \\(\\sum c_n z^n\\) converges absolutely for all \\(|z| < |b|\\).'],
  ['pmain', 'Now suppose that there is an integer \\(d\\) such that \\(\\sum c_n d^n\\) diverges. If \\(|z| > |d|\\), then \\(\\sum c_n z^n\\) diverges.'],
  ['pmain', 'Let there be set \\(S\\) which includes all values of \\(z\\) where \\(\\sum c_n z^n\\) would converge. If the series diverges whenever \\(|z| > |d|\\), then \\(|d|\\) must be an upper bound for the set, and \\(-|d|\\) must be a lower bound (i.e. all values of \\(z\\) in \\(S\\) must satisfy \\(-d < z < d\\)). This means that there must be some positive value \\(R\\) such that the series converges for all \\(-R < z < R\\). In other words, \\(-R\\) is the greatest upper bound for set \\(S\\) while \\(R\\) is the least upper bound. In such a case, \\(R\\) is called the <b>radius of convergence</b>.'],
  ['pmain', 'Earlier we saw that if there exists some integer \\(b \\ne 0\\) for which \\(\\sum c_n b^n\\) converges, then \\(\\sum c_n z^n\\) converges absolutely for all \\(|z| < |b|\\). If you choose any \\(z\\) in the set \\(S\\), you can also choose \\(b\\) such that \\(z < b < R\\), and show that the series converges absolutely for that \\(z\\). This fact that be used to show that the series \\(\\sum c_n z^n\\) converges absolutely when \\(|z| < R\\).'],
  ['pmain', 'One might think that the interval of convergence can be uneven. For example, instead of the series converging for values: \\(-R < x-a < R\\), the series can covergences for: \\(-M < x-a < R\\) where \\(M \\ne R\\). According to the ratio test, a series \\(\\sum_{n=1}^\\infty t_n\\) is convergent if \\(\\lim_{n \\to \\infty} \\left| \\frac{t_{n+1}}{t_n} \\right|<1\\). Let\'s apply this test for the series \\(\\sum_{n=1}^\\infty c_n (x-a)^n\\):'],
  ["displayFormula","\\[\\begin{gather} -1 < \\lim_{n \\to \\infty} \\frac{c_{n+1}(x-a)^{n+1}}{c_n(x-a)^n} < 1 \\\\  -1 < \\lim_{n \\to \\infty} \\frac{c_{n+1}}{c_n} (x-a) < 1 \\end{gather} \\]"],
  ['pmain', 'Let the limit be \\(\\lim_{n \\to \\infty} \\frac{c_{n+1}}{c_n} = L\\):'],
  ["displayFormula","\\[\\begin{align} -1 < L (x-a) < 1 \\\\ -\\frac{1}{L} < (x-a) < \\frac{1}{L} \\end{align} \\]"],
  ['pmain', 'Let \\(L = R\\):'],
  ["displayFormula","\\[-R < (x-a) < R \\]"],
  ['pmain', 'This shows that if it\'s true that the series converges when the ratio between the terms as \\(n\\) goes to infinity is between -1 and 1, then it\'s also true that the series converges when \\(x-a\\) is between \\(-R\\) and \\(R\\) for some real number \\(R\\). Therefore, the interval is not uneven.'],
];
export default content;