export const title="(Parabola) the equivalence of the focus-directrix definition and the conic section definition";
const content = [
  ['h1', 'The Equivalence Of The Focus-Directrix Definition And The Conic Section Definition Of A Parabola'], ['pmain', 'Here I have a <span style="color:darkblue">cone</span> and a plane <span style="color:sandybrown">P</span> intersecting it:'], ['displayimg', 'parabola1.PNG'], ['pmain', 'Here is a 2D view perpendicular to <span style="color:sandybrown">P</span>:'], ['displayimg', 'parabola2.PNG'], ['pmain', 'The plane <span style="color:sandybrown">P</span> is parallel to the <span style="color:darkblue">cone</span>\'s surface:'], ['displayimg', 'parabola3.PNG'],
  ['pmain', 'Let there be a sphere <span style="color:maroon">S</span> inside the cone such it touches the plane <span style="color:sandybrown">P</span> at one point. This sphere is tangent to both the <span style="color:darkblue">cone</span> and the plane <span style="color:sandybrown">P</span>:'], ['displayimg', 'parabola4.PNG'], ['pmain', 'Let plane <span style="color:rgb(0,113,162)">B</span> be a plane where the sphere touches the cone:'], ['displayimg', 'parabola5.PNG'], ['pmain', 'Let point <span style="color:red">F</span> be the point at which the sphere is touching plane <span style="color:sandybrown">P</span>:'], ['displayimg', 'parabola6.PNG'], ['pmain', 'Choose a random point X on the intersection:'], ['displayimg', 'parabola7.PNG'], ['pmain', 'Draw a line from X along the <span style="color:darkblue">cone</span> directly down to plane <span style="color:rgb(0,113,162)">B</span>, touching the sphere. Let\'s call that point <span style="color:chocolate">M</span>:'], ['displayimg', 'parabola8.PNG'],
  ['pmain', 'Line <span class="overLine">X<span style="color:chocolate">M</span></span> is the shortest path on the <span style="color:darkblue">cone</span> from X to a point that touches both the sphere and plane <span style="color:rgb(0,113,162)">B</span>, and since it lies on the cone, that means it\'s a tangent to the sphere. If we draw a line from X to <span style="color:red">F</span>, then that line will also be tangent to the sphere, since plane <span style="color:sandybrown">P</span> touches the sphere at one point, and that point being <span style="color:red">F</span>. Since two tangents meeting at the same point would be equal in length, then ||<span class="overLine">X<span style="color:red">F</span></span> = <span class="overLine">X<span style="color:chocolate">M</span></span>||. We can say that for any value of X, if we choose any random point X from the intersection, and draw a line to a point <span style="color:chocolate">M</span>, such that <span class="overLine">X<span style="color:chocolate">M</span></span> is the shortest path on the <span style="color:darkblue">cone</span> that\'s from X to a point that touches both the sphere and plane <span style="color:rgb(0,113,162)">B</span>, then ||<span class="overLine">X<span style="color:red">F</span></span> = <span class="overLine">X<span style="color:chocolate">M</span></span>||. We will now define the last three points, Y, Z and <span style="color: green;">G</span>:'],
  ['displayimg', 'parabola9.jpg'],
  ['pmain', 'Y is a point such that a plane on <span class="overLine">YX</span> would be parallel to <span style="color:rgb(0,113,162)">B</span>, and it lies on the line of the cone that is parallel to <span style="color:sandybrown">P</span>. Z is a point such that it lies on the intersection of the sphere and plane <span style="color:rgb(0,113,162)">B</span>, and that line <span class="overLine">YZ</span> would be the shortest line on the <span style="color:darkblue">cone</span> from Y to the plane <span style="color:rgb(0,113,162)">B</span>. Note that the line <span class="overLine">YZ</span> is parallel to <span style="color:sandybrown">P</span>. Lastly, point <span style="color:green">G</span> lies on the intersection of planes <span style="color:rgb(0,113,162)">B</span> and <span style="color:sandybrown">P</span>. It is a point such that <span class="overLine">X<span style="color:green">G</span></span> would be the shortest line on <span style="color:sandybrown">P</span> from X to plane <span style="color:rgb(0,113,162)">B</span>. Since ||<span class="overLine">X<span style="color:chocolate">M</span></span>|| and ||<span class="overLine">YZ</span>|| are tangents from the same <span style="color:darkblue">cone</span>, we can conclude:'],
  ['displayFormula', '\\[\\Vert YZ \\Vert = \\Vert X {\\color{brown} M} \\Vert = \\Vert X {\\color{red} F} \\Vert\\]'],
  ['pmain', 'Since <span class="overLine">X<span style="color:green">G</span></span> is parallel to <span class="overLine">YZ</span>, we can conclude:'],
  ['displayFormula', '\\[ \\Vert X {\\color{green} G} \\Vert = \\Vert YZ \\Vert = \\Vert X {\\color{brown} M} \\Vert = \\Vert X {\\color{red} F} \\Vert \\]'],
  ['pmain', 'Thus, we have shown that ||<span class="overLine">X<span style="color:green">G</span></span>|| = ||<span class="overLine">X<span style="color:red">F</span></span>||. No matter what X we choose, <span style="color:red">F</span> will remain the same, while <span style="color:green">G</span> could change but will always lie on the line that is the intersection of planes <span style="color:sandybrown">P</span> and <span style="color:rgb(0,113,162)">B</span>. With that line as the directrix, and point <span style="color:red">F</span> as the focus, we can say that the intersection of the plane <span style="color:sandybrown">P</span> and the <span style="color:darkblue">cone</span> is a parabola.']
];
export default content;