export const title="Proof Of The Addition Formulas And Subtraction Rule For tan(x)";
const content = [
  ['h1', 'Proof Of The Addition Formulas And Subtraction Rule For tan(x)'], ['pmain', 'Before reading the proof, you must be familiar with the addition and subtraction rule for cosine\nand sine. As for the proof, first lets start by dividing <span style="color:#3366FF">sin(<span style="color:#CC0099">j</span> - <span style="color:purple">k</span>)</span> by <span style="color:#006699">cos(<span style="color:#CC0099">j</span> - <span style="color:purple">k</span>)</span>:'], ['displayimg', 'tan1.png'], ['pmain', 'Now lets divide both the numerator and the denominator by <span style="color:#006699">cos(<span style="color:#CC0099">j</span>)cos(<span style="color:purple">k</span>)</span>:'],
  ['displayimg', 'tan2.png'], ['pmain', 'We already know that <span style="color:#11BBDD">tan(<span style="color:red">x</span>)</span> is [<span style="color:#3366FF">sin(<span style="color:red">x</span>)</span>/<span style="color:#006699">cos(<span style="color:red">x</span>)</span>], so:'], ['displayimg', 'tan3.png'], ['pmain', 'And that is the subtraction formula for <span style="color:#11BBDD">tan(<span style="color:red">x</span>)</span> As for the addition rule, we do the same thing we did above but with <span style="color:#3366FF">sin(<span style="color:#CC0099">j</span> + <span style="color:purple">k</span>)</span> and\n<span style="color:#006699">cos(<span style="color:#CC0099">j</span> + <span style="color:purple">k</span>)</span> instead:'], ['displayimg', 'tan4.png'],
  ['pmain', 'Now lets divide both the numerator and the denominator by <span style="color:#006699">cos(<span style="color:#CC0099">j</span>)cos(<span style="color:purple">k</span>)</span>:'], ['displayimg', 'tan5.png'], ['pmain', 'We already know that <span style="color:#11BBDD">tan(<span style="color:red">x</span>)</span> is [<span style="color:#3366FF">sin(<span style="color:red">x</span>)</span>/<span style="color:#006699">cos(<span style="color:red">x</span>)</span>], so:'],
  ['displayimg', 'tan6.png'],
  ['pmain', 'And that is the addition formula for <span style="color:#11BBDD">tan(<span style="color:red">x</span>)</span>. Now let\'s replace <span style="color:purple">k</span> with <span style="color:green">-z</span>.'],
  ['displayFormula', '\\[{\\color{deepskyblue}\\tan({\\color{orchid}j} + {\\color{green}-z})} = \\frac{{\\color{deepskyblue}\\tan({\\color{orchid}j})} + {\\color{deepskyblue}\\tan({\\color{green}-z})}}{1- {\\color{deepskyblue}\\tan({\\color{orchid}j}) \\tan({\\color{green}-z})}}\\]'],
  ['pmain', 'Since <span style="color:#11BBDD">tan(<span style="color:red">-x</span>)</span> = <span style="color:#11BBDD">-tan(<span style="color:red">x</span>)</span>:'],
  ['displayFormula', '\\[{\\color{deepskyblue}\\tan({\\color{orchid}j} - {\\color{green}z})} = \\frac{{\\color{deepskyblue}\\tan({\\color{orchid}j})} - {\\color{deepskyblue}\\tan({\\color{green}z})}}{1 + {\\color{deepskyblue}\\tan({\\color{orchid}j}) \\tan({\\color{green}z})}}\\]'],
];
export default content;