export const title="Deriving the formula for arcosh(x)";
const content = [
  ['h1', 'Deriving The Formula For arcosh(x)'],
  ['pmain', 'Let \\(y= \\cosh(x)\\):'],
  ['displayFormula', '\\[ y = \\frac{e^x + e^{-x}}{2}\\]'],
  ['pmain', 'In order to find the formula for the inverse of \\(\\cosh\\) we need to make \\(x\\) the subject of the above formula.'],
  ['displayFormula', '\\[ 2y = e^x + e^{-x}\\]'],
  ['pmain', 'If we multiply both sides by \\(e^x\\):'],
  ['displayFormula', '\\[\\begin{gathered} 2ye^x = (e^x)^2 + 1 \\\\ (e^x)^2 - 2ye^x + 1 = 0 \\end{gathered}\\]'],
  ['pmain', 'Let \\(v = e^x\\):'],
  ['displayFormula', '\\[v^2 -2yv + 1 = 0 \\]'],
  ['pmain', 'We can use the quadratic formula here:'],
  ['displayFormula', '\\[v=\\frac{-(-2y) ± \\sqrt{(-2y)^2 - 4(1)(1)}}{2(1)} = \\frac{2y ± \\sqrt{4y^2 - 4}}{2} \\]'],
  ['pmain', 'Simplifying:'],
  ['displayFormula', '\\[v = \\frac{2y ± 2\\sqrt{y^2 - 1}}{2} = y ∓ \\sqrt{y^2 - 1} \\]'],
  ['pmain', 'Since \\(v=e^x\\):'],
  ['displayFormula', '\\[x = \\ln(y ∓ \\sqrt{y^2 - 1}) \\]'],
  ['pmain', 'The function \\(y=\\cosh(x)\\) has a domain of \\((-\\infty,\\infty)\\) and is an even function, so it\'s inverse will fail the vertical line test. To solve this, \\(\\operatorname{arcosh}(y)\\) is defined as the inverse of \\(\\cosh(x)\\) where \\(x \\in [0, \\infty)\\). This means the range of \\(\\operatorname{arcosh}(y)\\) is \\([0,\\infty)\\):'],
  ['displayFormula', '\\[\\begin{gathered} x = \\ln(y ∓ \\sqrt{y^2 - 1}) \\ge 0 \\\\ y ∓ \\sqrt{y^2 - 1} \\ge 1 \\end{gathered}\\]'],
  ['pmain', 'Let \\( \\sqrt{y^2 - 1}\\) always be negative.'],
  ['displayFormula', '\\[\\begin{gathered} y - \\sqrt{y^2 - 1} \\ge 1 \\\\ -\\sqrt{y^2 - 1} \\ge 1-y \\\\ \\sqrt{y^2 - 1} \\le y-1 \\end{gathered}\\]'],
  ['pmain', 'If we square both sides:'],
  ['displayFormula', '\\[\\begin{gathered} y^2 - 1 \\le (y-1)^2 \\\\ y^2 - 1 \\le y^2 -2y +1 \\\\ -2 \\le -2y \\end{gathered}\\]'],
  ['pmain', 'The range of \\(y=\\cosh(x)\\) is \\([1,\\infty)\\). This means the above inequality is false. Therefore, \\( \\sqrt{y^2 - 1}\\) cannot be negative. Let\'s say it\'s positive instead:'],
  ['displayFormula', '\\[\\begin{gathered} y + \\sqrt{y^2 - 1} \\ge 1 \\\\ \\sqrt{y^2 - 1} \\ge 1-y \\\\ y^2 - 1 \\ge 1-2y+y^2 \\end{gathered}\\]'],
  ['pmain', 'This means:'],
  ['displayFormula', '\\[\\begin{gathered}  y^2 - 1 \\ge 1-2y+y^2 \\\\ -2 \\ge -2y \\end{gathered}\\]'],
  ['pmain', 'The above inequality is true for \\(y \\in [1,\\infty)\\). Therefore, \\( \\sqrt{y^2 - 1}\\) is always positive:'],
  ['displayFormula', '\\[\\operatorname{arcosh}(y) = \\ln(y + |\\sqrt{y^2 - 1})| \\]'],
];
export default content;