export const title="(Ellipse) The equivalence of the focus-directrix definition and the geometric definition";
const content = [
  ['h1', 'The Equivalence Of The Focus-Directrix Definition And The Geometric Definition'],
  ['pmain', 'The definition of an <b>ellipse</b> is the set of all points for which the sum of their distances from two fixed points (the foci) is constant. Consider an ellipse where is centre is at the origin:'],
  ['figure', ['e1.png','Image from openstax.org (Calculus Volume 2)']],
  ['pmain', 'The points \\(P\\) and \\(P\'\\) are located at the ends of the major axis of the ellipse, and have coordinates \\((a,0)\\) and \\((-a,0)\\), respectively. The length of the major axis in this ellipse is \\(2a\\). The points \\(Q\\) and \\(Q\'\\) are located at the ends of the minor axis of the ellipse, and have coordinates \\((0,b)\\) and \\((0,-b)\\), respectively. Using these definitions, <a href="./getting_the_standard_form_equation_from_the_geometric_definition">we can derive the standard form equation</a>:'],
  ["displayFormula","\\[ \\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1 \\]"],
  ['pmain', 'Choose a point \\(A\\) in the ellipse. Let \\(d_A\\) be the distance from \\(A\\) to one of the focus (we will only consider the right focus for now). Now image a horizontal line from \\(A\\) of length \\(d_A\\). Call the other end of this line \\(E\\):'],
  ['displayimg', 'e5.gif'],
  ['pmain', 'We chose the length of the horizontal line such that \\(\\Vert FA \\Vert = \\Vert AE \\Vert \\). Now consider two points on the ellipse, one at \\((0,b)\\), and the other at \\((a,0)\\). We will call them \\(X_1\\) and \\(X_2\\) respectively:'],
  ['displayimg', 'e6.png'],
  ['pmain', '\\(E_1\\) and \\(E_2\\) are chosen such that \\(\\Vert F \\ X_1 \\Vert = \\Vert X_1 \\ E_1 \\Vert \\) and \\(\\Vert F \\ X_2 \\Vert = \\Vert X_2 \\ E_2 \\Vert \\). Choose a number \\(k>0\\), and let the lines from \\(X_i\\) to \\(E_i\\) be stretched or shrinked by a factor of \\(k\\). In other words \\(\\Vert X_i \\ E_i \\Vert = \\Vert F \\ X_i \\Vert * k\\).'],
  ['displayimg', 'e7.gif'],
  ['pmain', 'Let \\(P_x\\) be a function that gives only the \\(x\\) position of a point, so \\(P_x(E_1) = ak\\). Since \\(\\Vert P_x(X_2) = a \\Vert \\) and \\(\\Vert X_2 \\ E_2 \\Vert = \\Vert F \\ X_2 \\Vert * k\\), then:'],
  ["displayFormula","\\[\\begin{align} P_x(E_2) &= P_x(X_2) + \\Vert X_2 \\ E_2 \\Vert \\\\ & = (a) + ((a-c) * k)  \\\\ & = ak + (a -ck) \\end{align}\\]"],
  ['pmain', 'Since \\(P_x(E_1) = ak\\) and \\(P_x(E_2) = ak + (a-ck)\\), then \\(P_x(E_2) = P_x(E_1) + (a-ck)\\). Let there be a number \\(h>0\\) such that \\((a=ch)\\), or \\(a-ch=0\\). Since \\(P_x(E_2) = P_x(E_1) + (a-ck)\\):'],
  ["displayFormula","\\[\\begin{align} k=h &\\implies a - ck = 0 \\implies P_x(E_2) = P_x(E_1) \\\\ k <h &\\implies a - ck > 0 \\implies P_x(E_2) > P_x(E_1) \\\\ k > h &\\implies a-ck < 0 \\implies P_x(E_2) < P_x(E_1) \\end{align}\\]"],
  ['pmain', 'This means \\(h\\) is a unique value such that \\(P_x(E_2) = P_x(E_1)\\). If \\(a=ch\\), then \\(h=\\frac{a}{c}\\). When \\(k=h\\), \\(P_x(E_1) = a * \\frac{a}{c}\\). This means \\(x=\\frac{a^2}{c}\\) is the line where \\(E_1\\) lies. Since \\(E_2\\) has the same \\(x\\) position at \\(k=h\\). Therefore, \\(E_2\\) also lies on the line \\(x=\\frac{a^2}{c}\\):'],
  ['displayimg', 'e8.png'],
  ['pmain', 'Now choose a new random point \\(A=(x_A,y_A)\\) on the ellipse, and let there be a horizontal line going from \\(A\\) to some point \\(E_A\\). Is it true that when \\(k=h\\) and \\(P_x(E_1)\\) lies on \\(x=\\frac{a^2}{c}\\), then \\(P_x(E_A)\\) would also lie on \\(x=\\frac{a^2}{c}\\)? The length from \\(A\\) to \\(F\\) is \\(\\sqrt{(y_A)^2 + (x_A-c)^2}\\):'],
  ['displayimg', 'e9.png'],
  ['pmain', 'Let there be \\(j > 0\\), such that when \\(k=j\\), \\(P_x (E_1) = P_x (E_A)\\). This means:'],
  ["displayFormula","\\[\\begin{gather} P_x(E_1) = ak \\\\ \\Vert A \\ E_A \\Vert = \\sqrt{(y_A)^2 + (x_A-c)^2} * k \\implies P_x(E_A) = \\sqrt{(y_A)^2 + (x_A-c)^2} * k + x_A \\\\ \\therefore aj =\\sqrt{(y_A)^2 + (x_A-c)^2} * j + x_A \\end{gather}\\]"],
  ['pmain', 'Rearranging:'],
  ["displayFormula","\\[\\begin{gather} aj-x_A =\\sqrt{(y_A)^2 + (x_A-c)^2} * j \\\\ (aj-x_A)^2 = ((y_A)^2 + (x_A-c)^2) * j^2 \\\\ a^2 j^2 -2 aj x_A + x_A^2 = j^2(y_A)^2 + j^2(x_A-c)^2 \\end{gather}\\]"],
  ['pmain', 'The equation for a point in an ellipse is:'],
  ["displayFormula","\\[\\begin{gather} \\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1 \\\\ y^2 = b^2 - \\frac{b^2 x^2}{a^2} \\end{gather}\\]"],
  ['pmain', 'Substituting for \\(y_A\\) in the previous equation:'],
  ["displayFormula","\\[\\begin{gather} a^2 j^2 -2 aj x_A + x_A^2 = j^2 \\left( b^2 - \\frac{b^2 x_A^2}{a^2} \\right) + j^2(x_A-c)^2 \\\\ a^2 j^2 -2 aj x_A + x_A^2 = j^2 b^2 - \\left( \\frac{j^2 b^2}{a^2} \\right) x_A^2 + j^2 x_A^2 - 2 j^2 x_A c + j^2 c^2  \\end{gather}\\]"],
  ['pmain', 'The coefficients of \\(x^2\\) should be equal on both sides. The same should be true for \\(x\\), and for the terms without any \\(x\\):'],
  ["displayFormula","\\[\\begin{gather} 1= \\left( \\frac{j^2 b^2}{a^2} \\right) + j^2 \\\\ -2aj = -2j^2c \\\\ a^2 j^2 = j^2 b ^2 + j^2 c^2\\end{gather}\\]"],
  ['pmain', 'Simplifying:'],
  ["displayFormula","\\[\\begin{gather} 1= j^2 * \\left( \\frac{ b^2}{a^2} +1\\right) \\\\ a = jc \\\\ a^2 = b ^2 + c^2\\end{gather}\\]"],
  ['pmain', 'The second equation tells us that \\(j = \\frac{a}{c}\\), which is the same value of \\(k\\) we got before with \\(E_2\\). This means when \\(\\Vert A \\ E_A \\Vert = \\Vert A \\ F \\Vert * \\frac{a}{c}\\), then \\(P_x(E_A) = P_x(E_1) = \\frac{a^2}{c}\\).'],
  ['displayimg', 'e10.png'],
  ['pmain', 'Thus, we have proven that for any point \\(A\\), the distance from point \\(A\\) to the line \\(x=\\frac{a^2}{c}\\) divided by the distance from point \\(A\\) to the focus is always constant, and this constant ratio is \\(\\frac{a}{c}\\). The line \\(x=\\frac{a^2}{c}\\) is called the <b>directrix</b>. This is the focus-directrix definition of an ellipse.'],

];
export default content;