export const title="Deriving the standard form equation of an ellipse from it's geometric definition";
const content = [
  ['h1', 'Deriving The Standard Form Equation Of An Ellipse From It\'s Geometric Definition'],
  ['pmain', 'The definition of an <b>ellipse</b> is the set of all points for which the sum of their distances from two fixed points (the foci) is constant. Consider an ellipse where is centre is at the origin:'],
  ['displayimg', 'e4.png'],
  ['pmain', 'The points \\(P\\) and \\(P\'\\) are located at the ends of the <b>major axis</b> of the ellipse, and have coordinates \\((a,0)\\) and \\((-a,0)\\), respectively. The major axis is always the longest distance across the ellipse, and can be horizontal or vertical. Thus, the length of the major axis in this ellipse is \\(2a\\). The points \\(Q\\) and \\(Q\'\\) are located at the ends of the <b>minor axis</b> of the ellipse, and have coordinates \\((0,b)\\) and \\((0,-b)\\), respectively. The minor axis is the shortest distance across the ellipse. The minor axis is perpendicular to the major axis.'],
  ['pmain', 'Let \\(F=(c,0)\\) and let \\(A\\) be a point of our choice. If \\(A=P\\) (i.e. \\(y=0\\) and \\(x=a\\)), then sum of the distances from \\(A\\) to both the foci is \\((a+c) + (a-c)\\) or \\(2a\\):'],
  ['displayimg', 'e2.png'],
  ['pmain', 'Since the sum of the distances from \\(A\\) to both the foci is constant, then for any \\(A\\), the sum of the distances would always be \\(2a\\). If \\(A=Q\\), then point \\(A\\) would be equidistant from the two foci, and so the distance from \\(A\\) to \\(F\\) would be \\(a\\). Using the Pythogorean theorem:'],
  ["displayFormula","\\[a^2 = b^2 + c^2\\]"],
  ['pmain', 'Consider the ellipse below:'],
  ['displayimg', 'e4.png'],
  ['pmain', 'Let \\((x,y)\\) be the coordinates of \\(A\\). The length of the smaller blue dashed line can be calculated using the Pythagorean theorem: \\(\\sqrt{(x-c)^2+y^2}\\). Similarly, the larger blue dashed line is \\(\\sqrt{(x-(-c))^2+y^2}\\) or \\(\\sqrt{(x+c)^2+y^2}\\). Since their sum is \\(2a\\):'],
  ["displayFormula","\\[\\begin{gather} \\sqrt{(x+c)^2+y^2} + \\sqrt{(x-c)^2+y^2} = 2a \\\\ \\sqrt{(x-c)^2+y^2} = 2a - \\sqrt{(x+c)^2+y^2}\\end{gather}\\]"],
  ['pmain', 'Squaring both sides:'],
  ["displayFormula","\\[\\begin{gather} (x-c)^2+y^2 = 4a^2 - 4a\\sqrt{(x+c)^2+y^2} + (x+c)^2+y^2 \\\\ (x-c)^2 = 4a^2 - 4a\\sqrt{(x+c)^2+y^2} + (x+c)^2\\end{gather}\\]"],
  ['pmain', 'Expanding:'],
  ["displayFormula","\\[\\begin{gather} x^2-2xc+c^2 = 4a^2 - 4a\\sqrt{(x+c)^2+y^2} + x^2 + 2xc +c^2\\\\ -4xc = 4a^2 - 4a\\sqrt{(x+c)^2+y^2} \\\\ -xc = a^2 - a\\sqrt{(x+c)^2+y^2} \\end{gather}\\]"],
  ['pmain', 'Rearranging:'],
  ["displayFormula","\\[\\begin{gather} \\frac{xc + a^2}{a}= \\sqrt{(x+c)^2+y^2} \\\\ \\frac{xc}{a} + a= \\sqrt{(x+c)^2+y^2} \\\\ \\left( \\frac{xc}{a} + a \\right)^2 = (x+c)^2+y^2 \\end{gather}\\]"],
  ['pmain', 'Expanding again:'],
  ["displayFormula","\\[\\begin{gather} \\left( \\frac{xc}{a}\\right)^2 + 2xc + a^2 = x^2 + 2xc +c^2+y^2 \\\\ \\left( \\frac{c}{a}\\right)^2 x^2 + a^2 = x^2 +c^2+y^2 \\end{gather}\\]"],
  ['pmain', 'Rearranging again:'],
  ["displayFormula","\\[\\begin{gather} \\left(\\left( \\frac{c}{a}\\right)^2 - 1\\right) x^2 = c^2 - a^2 +y^2 \\\\ \\frac{c^2 - a^2}{a^2} x^2 = c^2 - a^2 +y^2 \\end{gather}\\]"],
  ['pmain', 'Since \\(a^2 = b^2 + c^2\\):'],
  ["displayFormula","\\[\\begin{gather} \\frac{-b^2}{a^2} x^2 = -b^2 +y^2 \\\\ \\frac{-b^2}{a^2} x^2 -y^2 = -b^2 \\end{gather}\\]"],
  ['pmain', 'Now we finally we a simple equation for our ellipse:'],
  ["displayFormula","\\[ \\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1 \\]"],
  ['pmain', 'If the ellipse is shifted \\(h\\) units to the right and \\(k\\) units up:'],
  ["displayFormula","\\[ \\frac{(x-h)^2}{a^2} + \\frac{(y-k)^2}{b^2} = 1 \\]"],
];
export default content;