export const title="The equivalence of the geometric definition and the conic section definition of an ellipse";
const content = [
  ['h1', 'The Equivalence Of The Geometric Definition And The Conic Section Definition Of An Ellipse'],
  ['pmain', 'Consider the conic section below with a plane \\({\\color{green} G}\\) intersecting the cone:'],
  ['displayimg', 'c1.png'],
  ['pmain', 'By definition of an ellipse, the intersection of this plane and the cone is an <b>ellipse</b>. Now consider a sphere inside the cone that touches the cone and touches the plane \\({\\color{green} G}\\) at one point:'],
  ['displayimg', 'c2.png'],
  ['pmain', 'The locus of all points where this sphere touches the cone is a circle. Let\'s call this circle \\(C_1\\), and let there be a plane \\(B_1\\) where this circle lies:'],
  ['displayimg', 'c3.png'],
  ['pmain', 'The side view looks like this:'],
  ['displayimg', 'c4.png'],
  ['pmain', 'Let \\(O_1\\) be the centre of this shpere. A line from \\(O_1\\) to the point where the shpere touches plane \\({\\color{green} G}\\) and a line from \\(O_1\\) to a point in circle \\(C_1\\) are both the radius of this sphere:'],
  ['displayimg', 'c5.png'],
  ['pmain', 'Since the sphere touches the plane at only one point, then this plane is tangent to the sphere. Let \\({\\color{red} F_1}\\) be the point where this sphere touches the planes \\({\\color{green} G}\\):'],
  ['displayimg', 'c6.png'],
  ['pmain', 'Choose any point \\(X\\) in the ellipse:'],
  ['displayimg', 'c7.png'],
  ['pmain', 'The line from \\(X\\) to \\(F_1\\) lies on plane \\({\\color{green} G}\\) is tangent to the sphere (as it touches the sphere at only one point even if the line was infinitely long). Similarly, the line from \\(X\\) to the closest point on the circle \\(C_1\\) is also a tangent to the sphere. Since they are both tangent, then they are equal in length:'],
  ['displayimg', 'c8.png'],
  ['pmain', 'Let the point in circle \\(C_1\\) which is closest to \\(X\\) be \\(X_{c1}\\):'],
  ['displayimg', 'c9.png'],
  ['pmain', 'Now consider another sphere inside the cone that touches the cone and touches the plane \\({\\color{green} G}\\) at one point:'],
  ['displayimg', 'c10.png'],
  ['pmain', 'Let point \\(F_2\\) be the point where the bigger sphere touches the plane \\({\\color{green} G}\\):'],
  ['displayimg', 'c11.png'],
  ['pmain', 'Let the the locus of all points where this big sphere touches the cone form the circle \\(C_2\\):'],
  ['displayimg', 'c12.png'],
  ['pmain', 'Let plane \\(B_2\\) be where this circle lies:'],
  ['displayimg', 'c13.png'],
  ['pmain', 'Planes \\(B_1\\) and \\(B_2\\) are parallel:'],
  ['displayimg', 'c14.png'],
  ['pmain', 'Choose a point \\(X\\) on the ellipse:'],
  ['displayimg', 'c15.png'],
  ['pmain', 'Let \\(X_{c2}\\) be a point in circle \\(C_2\\) such that \\(\\overline{XC_2}\\) lies on the cone and is the shortest distance from \\(X\\) to the circle \\(C_2\\). The lines \\(\\overline{XC_2}\\) and \\(\\overline{XF_2}\\) are both tangent to the sphere and therefore the same length:'],
  ['displayimg', 'c16.png'],
  ['pmain', 'So far we have concluded that for any point \\(X\\) in the ellipse:'],
  ["displayFormula","\\[\\begin{gather} \\Vert \\overline{X \\ F_1} \\Vert = \\Vert \\overline{X \\ X_{c1}} \\Vert \\\\ \\Vert \\overline{X \\ F_2} \\Vert = \\Vert \\overline{X \\ X_{c2}} \\Vert \\end{gather}\\]"],
  ['pmain', 'Since \\(B_1\\) and \\(B_2\\) are parallel, then the section of the cone between \\(B_1\\) and \\(B_2\\) form a conical frustrum:'],
  ['displayimg', 'c17.png'],
  ['pmain', 'Since all slant line on the surface of a frustrum are of equal length, then for all \\(X\\), the lines \\(\\overline{X_{c1} \\ X_{c2}}\\) have the same length:'],
  ['displayimg', 'c18.png'],
  ['pmain', 'Since \\(\\Vert \\overline{X_{c1} \\ X_{c2}} \\Vert = \\Vert \\overline{X \\ X_{c1}} \\Vert + \\Vert \\overline{X \\ X_{c2}} \\Vert \\), then \\(\\Vert \\overline{X \\ X_{c1}} \\Vert + \\Vert \\overline{X \\ X_{c2}} \\Vert \\) is a constant. Therefore:'],
  ["displayFormula","\\[\\begin{align} \\text{some constant} &= \\Vert \\overline{X \\ X_{c1}} \\Vert + \\Vert \\overline{X \\ X_{c2}} \\Vert \\\\ &= \\Vert \\overline{X \\ F_1} \\Vert + \\Vert \\overline{X \\ F_2} \\Vert \\end{align}\\]"],
  ['pmain', 'This means that another definition of ellipse could be: "the locus of all points such that the sum of the distances from two fixed points \\(F_1\\) and \\(F_2\\) is a constant".'],
];
export default content;