export const title="Proving the polar equation for an ellipse (where one of the foci is at the pole)";
const content = [
  ['h1', 'Proving The Polar Equation For An Ellipse'],
  ['pmain', 'Consider an ellipse where one of the foci is at the pole:'],
  ['displayimg', 'p1.png'],
  ['pmain', 'The eccentricity of an ellipse is:'],
  ["displayFormula","\\[ e= \\frac{c}{a} \\]"],
  ['pmain', 'The directrix of an ellipse lies at:'],
  ["displayFormula","\\[ x= \\frac{a^2}{c} \\]"],
  ['pmain', 'The <b>focal parameter</b> is the distance from the focus to the nearest directrix. For the positive side:'],
  ["displayFormula","\\[ p= \\frac{a^2}{c} - c = \\frac{a^2 - c^2}{c}\\]"],
  ['pmain', 'Let point \\(A\\) be a random point in the ellipse. In polar coordinates, \\(A= (\\theta_A, r(\\theta_A))\\). For simplicity, let \\(r_A = r(\\theta_A)\\), so \\(A= (\\theta_A, r_A))\\):'],
  ['displayimg', 'p2.png'],
  ['pmain', 'Let \\(d\\) be the shortest distance from \\(A\\) to the directrix:'],
  ['displayimg', 'p3.png'],
  ['pmain', 'The dotted line below has the length \\(r_A \\cos(\\theta_A)\\):'],
  ['displayimg', 'p4.png'],
  ['pmain', 'The focal parameter is the distance from the focus to the directrix. This means the sum of the length of the dotted line and the distance \\(d\\) should give the focal parameter:'],
  ["displayFormula","\\[ p= r_A \\cos(\\theta_A) + d\\]"],
  ['pmain', 'Let\'s figure out the value of \\(d\\). Since the distance from \\(A\\) to the focus divided by the distance from \\(A\\) to the directrix is \\(e\\), then:'],
  ["displayFormula","\\[ e = \\frac{r_A}{d} \\ implies d = \\frac{r_A}{e}\\]"],
  ['pmain', 'Therefore:'],
  ["displayFormula","\\[ p= r_A \\cos(\\theta_A) + \\frac{r_A}{e}\\]"],
  ['pmain', 'Multiplying both sides by \\(e\\):'],
  ["displayFormula","\\[ ep= er_A \\cos(\\theta_A) + r_A\\]"],
  ['pmain', 'Making \\(r_A\\) the subject:'],
  ["displayFormula","\\[ r_A = \\frac{ep}{(1 + e \\cos(\\theta_A))} \\]"],
  ['pmain', 'Through similar line of reasoning, you can derive an equation for the ellipse if the other focus was at the pole instead. For this, you will have to consider the other directrix:'],
  ["displayFormula","\\[ r_A = \\frac{ep}{(1 - e \\cos(\\theta_A))} \\]"],
  ['pmain', 'Similarly, if the major axis was on the \\(y\\)-axis:'],
  ["displayFormula","\\[ r_A = \\frac{ep}{(1 ± e \\sin(\\theta_A))} \\]"],

];
export default content;