export const title="Finding the components of the acceleration vector";
const content = [
  ['h1', 'Finding The Components Of The Acceleration Vector'],
  ['pmain', 'Imagine a curve \\(C\\) made by tracing out a \\(\\textbf{r}(t)\\), where \\(\\textbf{r}(t)\\) represents the position of an object and is twice-differentiable.'], 
  ['displayimg', '1.png'], 
  ['pmain', 'Let \\(\\textbf{T}(t)\\) be the unit tangent vector to \\(C\\):'],
  ['displayFormula', '$$ \\textbf{T}(t) = \\frac{ \\textbf{r}\'(t) }{ \\Vert \\textbf{r}\'(t) \\Vert} $$'],
  ['pmain', 'let \\(\\textbf{N}(t)\\) be the principle unit normal vector to \\(C\\):'],
  ['displayFormula', '$$ \\textbf{N}(t) = \\frac{ \\textbf{T}\'(t) }{ \\Vert \\textbf{T}\'(t) \\Vert} $$'],
  ['pmain', 'Let \\(\\textbf{a}(t)\\) be the acceleration vector that lies in the plane formed by \\(\\textbf{T}(t)\\) and \\(\\textbf{N}(t)\\).'],
  ['pmain', 'Let \\(\\textbf{v}(t)=\\textbf{r}\'(t)\\) be the velocity vector. This means:'],
  ['displayFormula', '$$ \\textbf{T}(t) = \\frac{ \\textbf{r}\'(t) }{ \\Vert \\textbf{r}\'(t) \\Vert} \\implies \\begin{align} \\textbf{r}\'(t) &= \\Vert \\textbf{r}\'(t) \\Vert \\textbf{T}(t) \\\\  \\textbf{v}(t) &= \\Vert \\textbf{v}(t) \\Vert \\textbf{T}(t) \\end{align}$$'],
  ['pmain', 'Let \\(v(t)=\\Vert \\textbf{v}(t) \\Vert \\) be the speed, which is a scalar value. If we differentiate the above:'],
  ['displayFormula', '$$\\begin{align} \\textbf{a}(t)=\\textbf{v}\'(t)=\\frac{d}{dt} (v(t) \\textbf{T}(t)) &= v \'(t) \\textbf{T}(t) + v(t) \\textbf{T}\'(t) \\\\ &= v \'(t) \\textbf{T}(t) + v(t) \\Vert \\textbf{T}\'(t) \\Vert \\textbf{N}(t)\\end{align}$$'],
  ['pmain', 'Let \\(k\\) be the curvature:'],
  ['displayFormula', '$$k = \\frac{\\Vert\\textbf{T}\'(t) \\Vert}{\\Vert\\textbf{r}\'(t) \\Vert} \\implies \\Vert\\textbf{T}\'(t) \\Vert = k \\Vert\\textbf{r}\'(t) \\Vert = k \\ v(t)$$'],
  ['pmain', 'Therefore:'],
  ['displayFormula', '$$ \\textbf{a}(t)= v \'(t) \\textbf{T}(t) + [v(t)]^2 \\ k \\ \\textbf{N}(t)$$'],
  ['pmain', 'The coefficients of \\(\\textbf{T}(t)\\) and \\(\\textbf{N}(t)\\) are referred to as the <b>tangential component</b> of acceleration and the <b>normal component</b> of acceleration. We write \\(a_\\textbf{T}\\) to denote the tangential component and \\(a_\\textbf{N}\\) to denote the normal component.'],
  ['displayFormula', '$$\\begin{align} a_\\textbf{T} &= v \'(t) \\\\ a_\\textbf{N} &= [v(t)]^2 \\ k \\\\ \\textbf{a}(t) &= a_\\textbf{T} \\textbf{T}(t) + a_\\textbf{N} \\textbf{N}(t) \\end{align}$$'],
  ['pmain', 'If we take the dot product of both sides with \\(\\textbf{T}(t)\\):'],
  ['displayFormula', '$$\\begin{align} \\textbf{a}(t) \\cdot \\textbf{T}(t) &=a_\\textbf{T} \\textbf{T}(t) \\cdot \\textbf{T}(t) + a_\\textbf{N} \\textbf{N}(t) \\cdot \\textbf{T}(t) \\\\ \\textbf{a}(t) \\cdot \\textbf{T}(t) &=a_\\textbf{T} (\\textbf{T}(t) \\cdot \\textbf{T}(t)) + 0 \\\\ \\textbf{a}(t) \\cdot \\textbf{T}(t) &=a_\\textbf{T} (1) \\\\ \\textbf{a}(t) \\cdot \\textbf{T}(t) &=a_\\textbf{T} \\end{align}$$'],
  ['pmain', 'This means:'],
  ['displayFormula', '$$ a_\\textbf{T} = \\textbf{a}(t) \\cdot \\textbf{T}(t) = \\frac{\\textbf{v}(t) \\cdot \\textbf{a}(t)}{\\Vert \\textbf{v}(t) \\Vert }$$'],
  ['pmain', 'If we do \\(\\textbf{v}(t) \\times \\textbf{a}\\):'],
  ['displayFormula', '$$\\begin{align} \\textbf{v}(t) \\times \\textbf{a}(t) &= \\textbf{v}(t) \\times (a_\\textbf{T} \\textbf{T}(t) + a_\\textbf{N} \\textbf{N}(t)) \\\\ &= \\textbf{v}(t) \\times \\left(a_\\textbf{T} \\frac{\\textbf{v}(t)}{\\Vert \\textbf{v}(t) \\Vert} + a_\\textbf{N} \\textbf{N}(t) \\right) \\\\ &= \\left( \\textbf{v}(t) \\times a_\\textbf{T} \\frac{\\textbf{v}(t)}{\\Vert \\textbf{v}(t) \\Vert}\\right) + \\left( \\textbf{v}(t) \\times a_\\textbf{N} \\textbf{N}(t) \\right) \\end{align}$$'],
  ['pmain', 'Since \\(\\textbf{v}(t) \\times \\textbf{v}(t) = 0\\):'],
  ['displayFormula', '$$\\begin{align} \\textbf{v}(t) \\times \\textbf{a}(t) &= 0 + \\textbf{v}(t) \\times a_\\textbf{N} \\textbf{N}(t) \\\\ &= \\Vert \\textbf{v}(t) \\Vert \\textbf{T}(t) \\times a_\\textbf{N} \\textbf{N}(t) \\end{align}$$'],
  ['pmain', 'We can use "multiplication by a constant" property here:'],
  ['displayFormula', '$$\\begin{align} \\textbf{v}(t) \\times \\textbf{a}(t) &= \\Vert \\textbf{v}(t) \\Vert (\\textbf{T}(t) \\times a_\\textbf{N} \\textbf{N}(t)) \\\\ &= \\Vert \\textbf{v}(t) \\Vert a_\\textbf{N} (\\textbf{T}(t) \\times \\textbf{N}(t)) \\\\ \\Vert \\textbf{v}(t) \\times \\textbf{a}(t) \\Vert &= \\Vert \\textbf{v}(t) \\Vert a_\\textbf{N} \\ \\Vert \\textbf{T}(t) \\times \\textbf{N}(t) \\Vert \\end{align}$$'],
  ['pmain', 'Since \\(\\textbf{T}(t)\\) and \\(\\textbf{N}(t)\\) are perpendicular unit vector, \\(\\Vert \\textbf{T}(t) \\times \\textbf{N}(t) \\Vert = 1\\):'],
  ['displayFormula', '$$\\begin{gather} \\Vert \\textbf{v}(t) \\times \\textbf{a}(t) \\Vert = \\Vert \\textbf{v}(t) \\Vert a_\\textbf{N} \\\\ a_\\textbf{N} = \\frac{\\Vert \\textbf{v}(t) \\times \\textbf{a}(t) \\Vert}{\\Vert \\textbf{v}(t) \\Vert} \\end{gather}$$'],
  ['pmain', 'So we can conclude:'],
  ['displayFormula', '$$\\begin{align} a_\\textbf{T} &= \\frac{\\textbf{v}(t) \\cdot \\textbf{a}(t)}{\\Vert \\textbf{v}(t) \\Vert } \\\\ a_\\textbf{N} &= \\frac{\\Vert \\textbf{v}(t) \\times \\textbf{a}(t) \\Vert}{\\Vert \\textbf{v}(t) \\Vert} \\end{align}$$'],
  ['pmain', 'There is also another expression involving \\(a_\\textbf{N}\\) and \\(a_\\textbf{T}\\). First let\'s start \\(\\Vert \\textbf{a}(t) \\Vert ^2\\):'],
  ['displayFormula', '$$\\begin{align} \\Vert \\textbf{a}(t) \\Vert^2 &= \\textbf{a}(t) \\cdot \\textbf{a}(t)= (a_\\textbf{T} \\textbf{T}(t) + a_\\textbf{N} \\textbf{N}(t)) \\cdot (a_\\textbf{T} \\textbf{T}(t) + a_\\textbf{N} \\textbf{N}(t)) \\\\ &= a_\\textbf{T}^2 (\\textbf{T}(t) \\cdot \\textbf{T}(t)) + 2a_\\textbf{T}a_\\textbf{N} (\\textbf{T}(t) \\cdot \\textbf{N}(t)) + a_\\textbf{N}^2 (\\textbf{N}(t) \\cdot \\textbf{N}(t)) \\\\ &= a_\\textbf{T}^2 (1) + 0 + a_\\textbf{N}^2 (1) \\end{align}$$'],
  ['pmain', 'Therefore:'],
  ['displayFormula', '$$\\begin{align} a_\\textbf{N} = \\sqrt{\\Vert \\textbf{a}(t) \\Vert^2 - a_\\textbf{T}^2 } \\\\ a_\\textbf{T} = \\sqrt{\\Vert \\textbf{a}(t) \\Vert^2 - a_\\textbf{N}^2 } \\end{align} $$'],
];
export default content;