export const title="Antiderivative of arcsec(x)";
const content = [
  ['h1', 'Antiderivative Of arcsec(x)'],
  ['pmain', 'What we are trying to find is:'],
  ['displayFormula', '\\[ \\int \\operatorname{arcsec}(x) \\ dx \\]'],
  ['pmain', 'If \\(y = \\operatorname{arcsec}(x)\\), then \\(\\sec(x) = y\\). So:'],
  ['displayFormula', '\\[ \\frac{dx}{dy} = \\sec(y) \\tan(y) \\]'],
  ['pmain', 'This means:'],
  ['displayFormula', '\\[ \\int \\operatorname{arcsec}(x) \\ dx = \\int y \\sec(y) \\tan(y) \\ dy \\]'],
  ['pmain', 'To evaluate this, we can use integration by parts:'],
  ['displayFormula', '\\[ \\int u \\ dv = uv - \\int v \\ du\\]'],
  ['pmain', 'Let\'s define \\(u\\) and \\(v\\):'],
  ['displayFormula', '\\[\\begin{gathered} u = y,\\ du= dy \\\\ v = \\sec(y) ,\\ dv = \\sec(y) \\tan(y) dy \\end{gathered}\\]'],
  ['pmain', 'This means:'],
  ['displayFormula', '\\[ \\int y \\sec(y) \\tan(y) \\ dy = y \\sec(y) - \\int \\sec(y) \\ dy\\]'],
  ['pmain', 'The integral of \\(\\sec(y)\\) is derived <a href="./antiderivative_of_secant(x)">here</a>:'],
  ['displayFormula', '\\[ \\int y \\sec(y) \\tan(y) \\ dy = y \\sec(y) - \\ln |\\sec(y) + \\tan(y)| +C\\]'],
  ['pmain', 'Since \\(y = \\operatorname{arcsec}(x)\\):'],
  ['displayFormula', '\\[\\int y \\sec(y) \\tan(y) \\ dy =\\int \\operatorname{arcsec}(x) \\ dx =  \\operatorname{arcsec}(x) x - \\ln |x + \\tan(y)| +C\\]'],
  ['pmain', 'Using the Pythagorean theorem, we can say:'],
  ['displayFormula', '\\[ \\begin{align} \\tan^2(y) &= \\sec^2(y) -1 \\\\ \\tan(y) &= ±\\sqrt{x^2 -1} \\end{align} \\]'],
  ['pmain', 'Therefore:'],
  ['displayFormula', '\\[\\int \\operatorname{arcsec}(x) \\ dx =  \\operatorname{arcsec}(x) x - \\ln |x ±\\sqrt{x^2 -1}| +C\\]'],
  ['pmain', 'The range of \\(y=\\operatorname{arcsec}(x)\\) is \\([0, \\frac{\\pi}{2}) \\cup (\\frac{\\pi}{2}, \\pi] \\). In a unit circle, \\(\\tan(y)\\) and \\(x=\\sec(y)\\) are either both positive (when \\(y \\in [0,\\frac{\\pi}{2})\\)) or both negative (when \\(y \\in (\\frac{\\pi}{2},\\pi] \\)).'],
  ['pmain', 'If \\(x\\), is negative, then \\(\\tan(y)\\) is also negative:'],
  ['displayFormula', '\\[\\begin{align} \\int \\operatorname{arcsec}(x) \\ dx &= \\operatorname{arcsec}(x) x - \\ln (-|x| -|\\sqrt{x^2 -1}|) +C \\\\ &= \\operatorname{arcsec}(x) x - \\ln (|x| + |\\sqrt{x^2 -1}|) +C \\end{align}\\]'],
  ['pmain', 'If \\(x\\), is positive, then \\(\\tan(y)\\) is also positive:'],
  ['displayFormula', '\\[ \\int \\operatorname{arcsec}(x) \\ dx = \\operatorname{arcsec}(x) x - \\ln (|x| + |\\sqrt{x^2 -1}|) +C\\]'],
  ['pmain', 'So for the entire domain:'],
  ['displayFormula', '\\[ \\int \\operatorname{arcsec}(x) \\ dx = \\operatorname{arcsec}(x) x - \\ln (|x| + |\\sqrt{x^2 -1}|) +C\\]'],
];
export default content;