export const title="Formulas for the curvature of a curve";
const content = [
  ['h1', 'Formulas For The Curvature Of A Curve'],
  ['pmain', 'First, we need an intuitive definition for the curvature. For flatter surface, the unit tangent doesn\'t change much when increasing the arc length. However, for curvier surfaces, the unit tangent vector changes a lot:'],
  ["displayimg","2.png"],
  ['pmain', 'Let \\(C\\) be a smooth curve in the plane or in space given. The <b>curvature</b> \\(k\\) of the curve is defined as:'],
  ["displayFormula","\\[ k(t) = \\left\\Vert \\frac{d \\ \\textbf{T}(t)}{d \\ s(t)}  \\right\\Vert \\]"],
  ['pmain', 'where \\(\\textbf{T}(t)\\) is the unit tangent vector. This is our first formula for the curvature. Using the chain rule, we know:'],
  ["displayFormula","\\[ \\frac{d \\ \\textbf{T}(t)}{dt} = \\frac{d \\ \\textbf{T}(t)}{d \\ s(t)} \\frac{d \\ s(t)}{dt} \\]"],
  ['pmain', 'Since \\(\\frac{d \\ s(t)}{dt} = \\Vert \\textbf{r}\'(t) \\Vert\\):'],
  ["displayFormula","\\[ \\begin{gather} \\textbf{T}'(t)= \\frac{d \\ \\textbf{T}(t)}{d \\ s(t)} \\Vert \\textbf{r}\'(t) \\Vert \\\\ \\frac{\\textbf{T}'(t)}{\\Vert \\textbf{r}\'(t) \\Vert}=\\frac{d \\ \\textbf{T}(t)}{d \\ s(t)}\\end{gather}\\]"],
  ['pmain', 'Substituting this into our formula for the curvature:'],
  ["displayFormula","\\[ k(t) = \\left\\Vert \\frac{\\textbf{T}'(t)}{\\Vert \\textbf{r}\'(t) \\Vert}\\right\\Vert = \\frac{\\Vert \\textbf{T}'(t) \\Vert}{\\Vert \\textbf{r}\'(t) \\Vert} \\]"],
  ['pmain', 'This is our second formula for the curvature. Since \\(\\textbf{T}(t) = \\frac{\\textbf{r}\'(t)}{\\Vert \\textbf{r}(t) \\Vert}\\):'],
  ["displayFormula","\\[ \\textbf{r}'(t) = \\Vert \\textbf{r}'(t) \\Vert \\textbf{T}(t) = \\frac{d \\ s(t)}{dt}\\textbf{T}(t) \\]"],
  ['pmain', 'Using the product rule for derivatives:'],
  ["displayFormula","\\[ \\textbf{r}''(t) = \\frac{d^2 \\ s(t)}{(dt)^2}\\textbf{T}(t) + \\frac{d \\ s(t)}{dt}\\textbf{T}'(t) \\]"],
  ['pmain', 'If we take the cross product of \\(\\textbf{r}\'(t)\\) and \\(\\textbf{r}\'\'(t)\\):'],
  ["displayFormula","\\[ \\textbf{r}'(t) \\times \\textbf{r}''(t) = \\left[ \\frac{d \\ s(t)}{dt}\\textbf{T}(t) \\right] \\times \\left[ \\frac{d^2 \\ s(t)}{(dt)^2}\\textbf{T}(t) + \\frac{d \\ s(t)}{dt}\\textbf{T}'(t) \\right] \\]"],
  ['pmain', 'Since cross product is distributive:'],
  ["displayFormula","\\[ \\textbf{r}'(t) \\times \\textbf{r}''(t) = \\left[ \\frac{d \\ s(t)}{dt}\\textbf{T}(t) \\times \\frac{d^2 \\ s(t)}{(dt)^2}\\textbf{T}(t)\\right] + \\left[ \\frac{d \\ s(t)}{dt}\\textbf{T}(t) \\times \\frac{d \\ s(t)}{dt}\\textbf{T}'(t)\\right]\\]"],
  ['pmain', 'Since \\(\\textbf{T} \\times \\textbf{T} = 0\\):'],
  ["displayFormula","\\[ \\textbf{r}'(t) \\times \\textbf{r}''(t) = \\frac{d \\ s(t)}{dt}\\textbf{T}(t) \\times \\frac{d \\ s(t)}{dt}\\textbf{T}'(t) \\]"],
  ['pmain', 'According to the "multiplication by a constant" rule of cross product:'],
  ["displayFormula","\\[ \\textbf{r}'(t) \\times \\textbf{r}''(t) = \\frac{d^2 \\ s(t)}{(dt)^2} \\left[ \\textbf{T}(t) \\times \\textbf{T}'(t) \\right] \\]"],
  ['pmain', 'Since \\(\\textbf{T}(t)\\) is a unit tangent vector, then it\'s magnitude is always 1. <a href="./self_dot_product_constant_means_dot_product_with_derivative_is_zero">If a vector has constant magnitude, then the derivative vector will always be orthogonal.</a> This means \\(\\textbf{T}(t)\\) and \\(\\textbf{T}\'(t)\\) are orthogonal, so \\(\\Vert \\textbf{T}(t)\\times \\textbf{T}\'(t) \\Vert = \\Vert \\textbf{T}(t) \\Vert \\ \\Vert \\textbf{T}\'(t) \\Vert\\). This means:'],
  ["displayFormula","\\[\\Vert \\textbf{r}'(t) \\times \\textbf{r}''(t) \\Vert = \\frac{d^2 \\ s(t)}{(dt)^2} \\Vert \\textbf{T}(t) \\times \\textbf{T}'(t) \\Vert = \\frac{d^2 \\ s(t)}{(dt)^2} \\Vert \\textbf{T}(t) \\Vert \\ \\Vert \\textbf{T}\'(t) \\Vert \\]"],
  ['pmain', 'Since \\(\\Vert \\textbf{T}(t) \\Vert = 1\\):'],
  ["displayFormula","\\[\\Vert \\textbf{r}'(t) \\times \\textbf{r}''(t) \\Vert = \\frac{d^2 \\ s(t)}{(dt)^2} \\Vert \\textbf{T}\'(t) \\Vert \\]"],
  ['pmain', 'This means:'],
  ["displayFormula","\\[\\begin{gather} \\Vert \\textbf{r}'(t) \\times \\textbf{r}''(t) \\Vert = \\Vert \\textbf{r}'(t) \\Vert^2 \\Vert \\textbf{T}\'(t) \\Vert \\\\ \\Vert \\textbf{r}'(t) \\times \\textbf{r}''(t) \\Vert = \\Vert \\textbf{r}'(t) \\Vert^3 k(t) \\end{gather}\\]"],
  ['pmain', 'This leads to the third formula for the curvature:'],
  ["displayFormula","\\[k(t) = \\frac{\\Vert \\textbf{r}'(t) \\times \\textbf{r}''(t) \\Vert}{\\Vert \\textbf{r}'(t) \\Vert^3} \\]"],
  ['pmain', 'Suppose the curve is on a two dimensional plane, and the curve follows is defined by the function \\(f(x)\\). Then we can define \\(\\textbf{r}(x) = x \\textbf{i} +f(x)\\textbf{j} + 0\\textbf{k}\\). This means:'],
  ["displayFormula","\\[\\begin{gather} \\textbf{r}'(x) = \\textbf{i} + f'(x) \\textbf{j} \\\\ \\textbf{r}''(x) = f''(x)\\textbf{j}\\end{gather}\\]"],
  ['pmain', 'If we take the cross product:'],
  ["displayFormula","\\[ \\textbf{r}'(x) \\times \\textbf{r}''(x) =f''(x) \\textbf{k} \\]"],
  ['pmain', 'Therefore:'],
  ["displayFormula","\\[k(x) = \\frac{\\Vert \\textbf{r}'(x) \\times \\textbf{r}''(x) \\Vert}{\\Vert \\textbf{r}'(x) \\Vert^3} = \\frac{\\Vert f''(x) \\textbf{k} \\Vert}{\\Vert \\textbf{r}'(x) \\Vert^3}= \\frac{| f''(x) |}{\\Vert \\textbf{r}'(x) \\Vert^3} \\]"],
  ['pmain', 'If \\(\\textbf{r}\'(x) = \\textbf{i} + f\'(x)\\textbf{j} \\), then \\(\\Vert \\textbf{r}\'(x) \\Vert = \\sqrt{1+ [f\'(x)]^2}\\):'],
  ["displayFormula","\\[k(x) = \\frac{| f''(x) |}{( 1+ [f\'(x)]^2 )^{\\frac{3}{2}}} \\]"],
  ['pmain', 'This is the fourth formula for the curvature.'],
];
export default content;