export const title="Deriving the formula for the radius of the curvature";
const content = [
  ['h1', 'Deriving The Formula For The Radius Of The Curvature'],
  ['pmain', 'Let \\(f(x)\\) be some continuous function, and choose a point on \\(f(x)\\):'],
  ["displayimg","3.png"],
  ['pmain', 'The <b>radius of a curvature</b> is the radius of a circle that has the same curvature as the curvature at your desired point of \\(f(x)\\):'],
  ["displayimg","4.png"],
  ['pmain', 'A circle that best approximates the curvature of a curve at a specific point is called an <b>osculating circle</b>. The equation of a circle is'],
  ["displayFormula","\\[ (x-h)^2 + (y-k)^2 = r^2 \\]"],
  ['pmain', 'where \\(r\\) is radius of the osculating circle (also called the radius of the curvature) and \\((h,k)\\) is the center of the osculating circle. If we derivate both sides with respect to \\(x\\).'],
  ["displayFormula","\\[\\begin{gather} 2(x-h) + 2(y-k)\\frac{dy}{dx} = 0 \\\\ (x-h) + (y-k)\\frac{dy}{dx} = 0  \\end{gather}\\]"],
  ['pmain', 'If we take the derivative again:'],
  ["displayFormula","\\[ 1 + \\frac{dy}{dx}*\\frac{dy}{dx} + (y-k)\\frac{d^2 y}{(dx)^2} = 0 \\]"],
  ['pmain', 'We can rearrange both of these equations to get:'],
  ["displayFormula","\\[\\begin{gather} (x-h) = -(y-k)\\frac{dy}{dx} \\\\ (y-k) = \\frac{-1 - \\left( \\frac{dy}{dx} \\right)^2}{\\frac{d^2 y}{(dx)^2}}\\end{gather}\\]"],
  ['pmain', 'If we substitute the expression for \\(y-k\\) into the first equation:'],
  ["displayFormula","\\[(x-h) = \\frac{1 + \\left( \\frac{dy}{dx} \\right)^2}{\\frac{d^2 y}{(dx)^2}}\\frac{dy}{dx} \\]"],
  ['pmain', 'If we substitute the expression for both \\(x-h\\) and \\(y-k\\) into the equation of the circle:'],
  ["displayFormula","\\[ \\left(\\frac{1 + \\left( \\frac{dy}{dx} \\right)^2}{\\frac{d^2 y}{(dx)^2}}\\frac{dy}{dx} \\right)^2 + \\left(\\frac{-1 - \\left( \\frac{dy}{dx} \\right)^2}{\\frac{d^2 y}{(dx)^2}} \\right)^2 = r^2 \\]"],
  ['pmain', 'Simplifying:'],
  ["displayFormula","\\[ \\left(\\frac{1 + \\left( \\frac{dy}{dx} \\right)^2}{\\frac{d^2 y}{(dx)^2}}\\right)^2 \\left(\\frac{dy}{dx} \\right)^2 + \\left(\\frac{1 + \\left( \\frac{dy}{dx} \\right)^2}{\\frac{d^2 y}{(dx)^2}} \\right)^2 = r^2 \\]"],
  ['pmain', 'Factoring:'],
  ["displayFormula","\\[ \\left(\\frac{1 + \\left( \\frac{dy}{dx} \\right)^2}{\\frac{d^2 y}{(dx)^2}}\\right)^2 \\left(\\left(\\frac{dy}{dx} \\right)^2 +1\\right) = r^2 \\]"],
  ['pmain', 'According to the power of a quotient rule:'],
  ["displayFormula","\\[ \\frac{\\left(1 + \\left( \\frac{dy}{dx} \\right)^2\\right)^2 }{\\left( \\frac{d^2 y}{(dx)^2}\\right)^2 }\\left(\\left(\\frac{dy}{dx} \\right)^2 +1\\right) = r^2 \\]"],
  ['pmain', 'Using the product rule (for exponents):'],
  ["displayFormula","\\[ \\frac{\\left(1 + \\left( \\frac{dy}{dx} \\right)^2\\right)^3 }{\\left( \\frac{d^2 y}{(dx)^2}\\right)^2 } = r^2 \\]"],
  ['pmain', 'The last step is to take the square root of both sides, and we get our formula for the radius of the curvature:'],
  ["displayFormula","\\[ \\frac{\\left(1 + \\left( \\frac{dy}{dx} \\right)^2\\right)^\\frac{3}{2} }{\\frac{d^2 y}{(dx)^2} } = r\\]"],
  ['pmain', 'We can rewrite this as:'],
  ["displayFormula","\\[ r= \\frac{\\left(1 + f'(x)^2\\right)^\\frac{3}{2} }{| f''(x) | } \\]"],
  ['pmain', 'If you know <a href="./curvature_formulas">the formula for the curvature</a>, you would notice how the radius is the reciprocal of the curvature itself:'],
  ["displayFormula","\\[ k= \\frac{| f''(x) | }{\\left(1 + f'(x)^2\\right)^\\frac{3}{2} } \\implies k=\\frac{1}{r} \\]"],
];
export default content;