export const title="Other ways to express the correlation coefficient";
const content = [
  ['h1', 'Other Ways To The Correlation Coefficient'], 
  ['pmain', 'The correlation coefficient is given by this formula:'],
  ['displayFormula', '\\[ \\operatorname{corr}(X,Y) =\\frac{\\operatorname{cov}(X,Y)}{\\sigma_X \\sigma_Y} \\]'], 
  ['pmain', 'Stated another way:'],
  ['displayFormula', '\\begin{align} \\operatorname{corr}(X,Y) &=  \\frac{\\frac{1}{n}\\sum^n_{i=1} (x_i - \\overline{x}) (y_i - \\overline{y})}{\\sigma_X \\sigma_Y} \\\\ &= \\frac{\\frac{1}{n}\\sum^n_{i=1} (x_i - \\overline{x}) (y_i - \\overline{y})}{\\sqrt{\\frac{\\sum^n_{i=1}(x_i - \\overline{x})^2}{n}} \\sqrt{\\frac{\\sum^n_{i=1}(y_i - \\overline{y})^2}{n}}} \\\\ &= \\frac{\\sum^n_{i=1} (x_i - \\overline{x}) (y_i - \\overline{y})}{\\sqrt{\\sum^n_{i=1} (x_i - \\overline{x})^2 } \\sqrt{\\sum^n_{i=1}(y_i - \\overline{y})^2}}\\end{align}'], 
  ['pmain', 'Rearranging the above:'],
  ['displayFormula', '\\begin{align} \\operatorname{corr}(X,Y) &= \\frac{\\sum^n_{i=1} (x_iy_i - x_i \\overline{y} - y_i\\overline{x} + \\overline{x}\\overline{y})}{\\sqrt{\\sum^n_{i=1} (x_i^2 - 2x_i \\overline{x} + \\overline{x}^2) } \\sqrt{\\sum^n_{i=1}(y_i^2 - 2 y_i \\overline{y}+ \\overline{y}^2)}} \\\\ \\\\ &= \\frac{\\sum^n_{i=1} x_iy_i - \\sum^n_{i=1} x_i \\overline{y} -\\sum^n_{i=1} y_i\\overline{x} + \\sum^n_{i=1}\\overline{x}\\overline{y}}{\\sqrt{\\sum^n_{i=1} x_i^2 - 2 \\sum^n_{i=1} x_i \\overline{x} + \\sum^n_{i=1} \\overline{x}^2 } \\sqrt{\\sum^n_{i=1}y_i^2 - 2 \\sum^n_{i=1}y_i \\overline{y}+ \\sum^n_{i=1} \\overline{y}^2}} \\\\ \\\\ &= \\frac{\\sum^n_{i=1} x_iy_i - n \\overline{x} \\overline{y} -n \\overline{y}\\overline{x} + n\\overline{x}\\overline{y}}{\\sqrt{\\sum^n_{i=1} x_i^2 - 2 n \\overline{x} \\overline{x} + n \\overline{x}^2 } \\sqrt{\\sum^n_{i=1}y_i^2 - 2 n \\overline{y} \\overline{y}+ n \\overline{y}^2}} \\\\ \\\\ &= \\frac{\\sum^n_{i=1} x_iy_i - n \\overline{x} \\overline{y}}{\\sqrt{\\sum^n_{i=1} x_i^2 - n \\overline{x}^2 } \\sqrt{\\sum^n_{i=1}y_i^2 - n \\overline{y}^2}} \\end{align}'], 
  ['pmain', 'We can multiply the numerator and denominator by \\(n\\):'],
  ['displayFormula', '\\begin{align} \\operatorname{corr}(X,Y) &= \\frac{n(\\sum^n_{i=1} x_iy_i - n \\overline{x} \\overline{y})}{n \\sqrt{\\sum^n_{i=1} x_i^2 - n \\overline{x}^2 } \\sqrt{\\sum^n_{i=1}y_i^2 - n \\overline{y}^2}} \\\\ \\\\ &= \\frac{n\\sum^n_{i=1} x_iy_i - n^2 \\overline{x} \\overline{y}}{\\sqrt{n^2} \\sqrt{\\sum^n_{i=1} x_i^2 - n \\overline{x}^2 } \\sqrt{\\sum^n_{i=1}y_i^2 - n \\overline{y}^2}} \\\\ \\\\ &= \\frac{n\\sum^n_{i=1} x_iy_i - n^2 \\overline{x} \\overline{y}}{\\sqrt{n\\sum^n_{i=1} x_i^2 - (n \\overline{x})^2 } \\sqrt{n\\sum^n_{i=1}y_i^2 - (n \\overline{y})^2}} \\\\ \\\\ &= \\frac{n\\sum^n_{i=1} x_iy_i - \\sum^n_{i=1} x_i \\sum^n_{i=1}y_i}{\\sqrt{n\\sum^n_{i=1} x_i^2 - (\\sum^n_{i=1} x_i)^2 } \\sqrt{n\\sum^n_{i=1}y_i^2 - (\\sum^n_{i=1} y_i)^2}} \\end{align}'], 
];
export default content;
