export const title="Surface area generated by a parametric equation";
const content = [
  ['h1', 'Surface Area Generated By A Parametric Equation'],
  ['pmain', 'Consider a solid formed by rotated a curve defined by the parametric equations \\(x=x(t)\\) and \\(y=y(t)\\) for \\(a \\le t \\le b\\) around the x-axis.'],
  ['pmain', 'Suppose we want to find the surface area of this solid between \\(t=a\\) and \\(t=b\\). Let \\(x(a) = \\alpha\\) and \\(x(b) = \\beta\\). Finding the surface area between \\(t=a\\) and \\(t=b\\) is the same as finding the surface area between \\(x = \\alpha\\) and \\(x = \\beta\\):'],
  ["displayFormula","\\[S = 2 \\pi \\int_\\alpha^\\beta y \\sqrt{1+ (\\frac{dy}{dx})^2} \\ dx\\]"],
  ['pmain', 'The integral with respect to \\(t\\) would be:'],
  ["displayFormula","\\[\\begin{align} S &= 2 \\pi \\int_a^b y(t) \\sqrt{1+ \\left(\\frac{dy/dt}{dx/dt} \\right)^2}\\ \\frac{dx}{dt} \\ dt \\\\ &= 2 \\pi \\int_a^b y(t) \\sqrt{ \\left( \\frac{dx}{dt} \\right)^2+ \\left( \\frac{dy}{dt} \\right)^2 } \\ dt \\end{align}\\]"],
];
export default content;