export const title="Proof For The Fundamental Thoerem Of Calculus, Part 2";
const content = [
  ['h1', 'Proof For The Fundamental Thoerem Of Calculus, Part 2'],
  ['pmain', 'The second fundamental theorem of calculus states that if <span style="color:blue">f</span> is continuous on [a, b], then:'],
  ['displayimg', '24.png'],
  ['pmain', 'where <span style="color:navy">F(<span style="color:black">x</span>)</span> is the antiderivative of <span style="color:blue">f</span>. Lets say the function <span style="color:blue">f</span> is continous on [a, b], and lets say function <span style="color:red">g</span> is defined by:'],
  ['displayimg', '11.png'],
  ['pmain', 'The variable x varies between a and b. Since <span style="color:red">g\'(<span style="color:black">x</span>)</span> = <span style="color:blue">f(<span style="color:black">x</span>)</span>. We can say that <span style="color:red">g(<span style="color:black">x</span>)</span> is the antiderivative of <span style="color:blue">f(<span style="color:black">x</span>)</span>. The antiderivative of a function has an arbitrary constant. For example, the antiderivative of [x<sup>2</sup>] is [(x<sup>3</sup>/3) + C], where C is an arbitrary constant. This is not the case with <span style="color:red">g(<span style="color:black">x</span>)</span>, since you can find the value of C by using <span style="color:red">g(<span style="color:black">a</span>)</span> = 0. For example if <span style="color:blue">f(<span style="color:black">x</span>)</span> = [x<sup>2</sup>], and if a = 6, then <span style="color:red">g(<span style="color:black">6</span>)</span> = [(6<sup>3</sup>/3) + C], this means that [C = -72].'],
  ['pmain','<span style="color:navy">F(<span style="color:black">x</span>)</span> is like <span style="color:red">g(<span style="color:black">x</span>)</span>, but where the arbitrary constant is unknown, so:'],
  ['displayimg', '21.png'],
  ['pmain', 'Where D is unknown. Now lets evaluate <span style="color:navy">F(<span style="color:black">b</span>)</span> - <span style="color:navy">F(<span style="color:black">a</span>)</span>:'],
  ['displayimg', '22.png'],
  ['pmain', 'If we expand <span style="color:red">g</span>:'], ['displayimg', '23.png'], ['pmain', 'Since <span style="color:red">g(<span style="color:black">a</span>)</span> = 0:'], ['displayimg', '24.png'],
  ['pmain', 'This is the fundamental theorem of calculus, part 2.'],
  ['pmain', 'The above proof assumes that <span style="color:blue">f</span> is continuous on the whole interval [a, b]. The proof below will assume that \\(f\\) is Riemann integrable on the interval \\([a, b]\\). Let \\(F\\) be an antiderivative \\(f\\) on \\((a, b)\\) such that \\(F\\) is continuous on \\([a, b]\\). Let there be numbers \\(x_0, \\ldots, x_n\\) such that:'],
  ['displayFormula','\\[a = x_0 < x_1 < \\ldots < x_{n-1} < x_n = b\\]'],
  ['pmain', 'It follows that:'],
  ['displayFormula','\\[\\begin{align} F(b) - F(a) &= F(x_n) - F(x_0) \\\\ &= F(x_n) - F(x_{n-1}) + F(x_{n-1}) - F(x_{n-2}) + F(x_{n-2}) - F(x_{n-3}) + \\ldots + F(x_2) - F(x_1) + F(x_1) - F(x_0) \\end{align}\\]'],
  ['pmain', 'We can rewrite this as:'],
  ['displayFormula','\\[F(b) - F(a) = \\sum_{i=1}^n F(x_i) - F(x_{i-1})\\]'],
  ['pmain', 'According to the mean value theorem, for each \\(i\\) there exists a \\(c_i\\) in \\((x_{i-1}, x_i)\\) such that:'],
  ['displayFormula','\\[ \\sum_{i=1}^n F(x_i) - F(x_{i-1}) = F\'(c_i)(x_i - x_{i-1})\\]'],
  ['pmain', 'Therefore:'],
  ['displayFormula','\\[\\begin{align} F(b) - F(a) &= \\sum_{i=1}^n F\'(c_i)(x_i - x_{i-1}) \\\\ &= \\sum_{i=1}^n f(c_i)(\\Delta x_i) \\end{align}\\]'],
  ['pmain', 'We are describing the area of a rectangle, with the width times the height, and we are adding the areas together. As the size of the partitions get smaller and n increases, resulting in more partitions to cover the space, we get closer and closer to the actual area of the curve.'],
  ['displayFormula','\\[\\lim_{\\Delta x_i \\to 0} F(b) - F(a) = \\lim_{\\Delta x_i \\to 0} \\sum_{i=1}^n f(c_i)(\\Delta x_i) \\]'],
  ['pmain','Neither F(b) nor F(a) is dependent on \\(\\Delta x_i\\):'],
  ['displayFormula','\\[F(b) - F(a) = \\lim_{\\Delta x_i \\to 0} \\sum_{i=1}^n f(c_i)(\\Delta x_i) \\]'],
  ['pmain','The expression on the right side of the equation defines the integral over \\(f\\) from \\(a\\) to \\(b\\):'],
  ['displayFormula','\\[F(b) - F(a) = \\int_a^b f(x) dx \\]'],
];
export default content;